/* 
 * This file is part of Stack Wallet.
 * 
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'dart:async';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:logger/logger.dart';

import '../../services/node_service.dart';
import '../../services/wallets.dart';
import '../../themes/stack_colors.dart';
import '../../utilities/flutter_secure_storage_interface.dart';
import '../../utilities/logger.dart';
import '../../utilities/prefs.dart';
import 'backup_testing/backup_file_handler.dart';
import 'backup_testing/wallet_restoration_manager.dart';
import 'backup_testing/transaction_test_executor.dart';
import 'testing_models.dart';
import 'test_suite_interface.dart';
import 'test_suites/monero_test_suite.dart';
import 'test_suites/wownero_test_suite.dart';
import 'test_suites/salvium_test_suite.dart';
import 'test_suites/epiccash_test_suite.dart';
import 'test_suites/firo_test_suite.dart';
import 'test_suites/litecoin_mweb_test_suite.dart';
import 'test_suites/tor_test_suite.dart';
import 'test_suites/bitcoin_test_suite.dart';
import 'test_suites/bitcoincash_test_suite.dart';

final testingServiceProvider = StateNotifierProvider<TestingService, TestingSessionState>((ref) {
  return TestingService();
});

class TestingService extends StateNotifier<TestingSessionState> {
  TestingService() : super(TestingSessionState(
    suiteStatuses: {
      for (var type in TestSuiteType.values) type: TestSuiteStatus.waiting
    },
    isRunning: false,
    completed: 0,
    total: TestSuiteType.values.length,
  ));

  final Map<TestSuiteType, TestSuiteInterface> _testSuites = {};
  final StreamController<TestingSessionState> _statusController = StreamController<TestingSessionState>.broadcast();
  bool _cancelled = false;
  
  // Enhanced backup testing components
  BackupFileHandler? _backupFileHandler;
  WalletRestorationManager? _walletRestorationManager;
  TransactionTestExecutor? _transactionTestExecutor;

  Stream<TestingSessionState> get statusStream => _statusController.stream;

  void _initializeTestSuites() {
    _testSuites[TestSuiteType.monero] = MoneroTestSuite();
    _testSuites[TestSuiteType.wownero] = WowneroTestSuite();
    _testSuites[TestSuiteType.salvium] = SalviumTestSuite();
    _testSuites[TestSuiteType.epicCash] = EpicCashTestSuite();
    _testSuites[TestSuiteType.firo] = FiroTestSuite();
    _testSuites[TestSuiteType.litecoinMWEB] = LitecoinMWEBTestSuite();
    _testSuites[TestSuiteType.tor] = TorTestSuite();
    // Phase 4: Bitcoin Ecosystem
    _testSuites[TestSuiteType.bitcoin] = BitcoinTestSuite();
    _testSuites[TestSuiteType.bitcoinCash] = BitcoinCashTestSuite();
  }

  Future<void> runAllTests() async {
    final config = state.currentConfiguration;
    
    // Determine which testing mode to use
    if (config?.mode == TestingMode.backupFile) {
      await runBackupFileTests();
    } else {
      // Default to programmed vectors
      await _runProgrammedVectorTests();
    }
  }

  Future<void> _runProgrammedVectorTests() async {
    if (state.isRunning) return;
    
    _cancelled = false;
    _initializeTestSuites();
    
    state = state.copyWith(
      isRunning: true,
      completed: 0,
      currentPhase: "Running programmed vector tests",
      suiteStatuses: {
        for (var type in TestSuiteType.values) type: TestSuiteStatus.waiting
      },
    );
    _statusController.add(state);

    try {
      for (final type in TestSuiteType.values) {
        if (_cancelled) break;

        await runTestSuite(type);
      }
    } catch (e) {
      Logging.instance.log(Level.error, "Error running test suites: $e");
    } finally {
      state = state.copyWith(
        isRunning: false,
        currentPhase: null,
      );
      _statusController.add(state);
    }
  }

  Future<void> runTestSuite(TestSuiteType type) async {
    if (_cancelled) return;

    final suite = _testSuites[type];
    if (suite == null) return;

    final updatedStatuses = Map<TestSuiteType, TestSuiteStatus>.from(state.suiteStatuses);
    updatedStatuses[type] = TestSuiteStatus.running;
    
    state = state.copyWith(suiteStatuses: updatedStatuses);
    _statusController.add(state);

    try {
      final result = await suite.runTests().timeout(
        const Duration(seconds: 30),
        onTimeout: () => const TestResult(
          success: false,
          message: "Test suite timed out",
          logs: ["Test execution exceeded 30 second timeout"],
          executionTime: Duration(seconds: 30),
        ),
      );

      if (_cancelled) return;

      updatedStatuses[type] = result.success ? TestSuiteStatus.passed : TestSuiteStatus.failed;
      
      final completed = updatedStatuses.values
          .where((status) => status == TestSuiteStatus.passed || status == TestSuiteStatus.failed)
          .length;

      state = state.copyWith(
        suiteStatuses: updatedStatuses,
        completed: completed,
      );
      _statusController.add(state);

      await suite.cleanup();
    } catch (e) {
      if (_cancelled) return;

      updatedStatuses[type] = TestSuiteStatus.failed;
      
      final completed = updatedStatuses.values
          .where((status) => status == TestSuiteStatus.passed || status == TestSuiteStatus.failed)
          .length;

      state = state.copyWith(
        suiteStatuses: updatedStatuses,
        completed: completed,
      );
      _statusController.add(state);

      Logging.instance.log(Level.error, "Error running $type test suite: $e");
    }
  }

  Future<void> cancelTesting() async {
    _cancelled = true;
    state = state.copyWith(isRunning: false);
    _statusController.add(state);
    
    for (final suite in _testSuites.values) {
      await suite.cleanup();
    }
  }

  Future<void> resetTestResults() async {
    // Clean up any existing test environment
    await _cleanupTestEnvironment();
    
    state = TestingSessionState(
      suiteStatuses: {
        for (var type in TestSuiteType.values) type: TestSuiteStatus.waiting
      },
      isRunning: false,
      completed: 0,
      total: TestSuiteType.values.length,
      currentConfiguration: null,
      currentPhase: null,
    );
    _statusController.add(state);
  }

  /// Configure testing mode and settings
  Future<void> configureTestingMode(TestConfiguration config) async {
    if (state.isRunning) {
      throw Exception("Cannot configure testing while tests are running");
    }

    state = state.copyWith(
      currentConfiguration: config,
      currentPhase: "Configuring testing mode",
    );
    _statusController.add(state);

    // Initialize backup testing components if needed
    if (config.mode == TestingMode.backupFile) {
      _backupFileHandler ??= BackupFileHandler();
      _walletRestorationManager ??= WalletRestorationManager();
      _transactionTestExecutor ??= TransactionTestExecutor();
      
      // Validate backup file if provided
      if (config.backupFilePath != null) {
        final isValid = await _backupFileHandler!.validateBackupFile(config.backupFilePath!);
        if (!isValid) {
          throw Exception("Invalid backup file: ${config.backupFilePath}");
        }
      }
    }

    state = state.copyWith(currentPhase: null);
    _statusController.add(state);
    
    Logging.instance.log(Level.info, "Testing mode configured: ${config.mode}");
  }

  /// Run backup file tests
  Future<void> runBackupFileTests() async {
    final config = state.currentConfiguration;
    if (config == null || config.mode != TestingMode.backupFile) {
      throw Exception("Backup file testing mode not configured");
    }

    if (config.backupFilePath == null || config.backupPassphrase == null) {
      throw Exception("Backup file path and passphrase required");
    }

    if (state.isRunning) return;
    
    _cancelled = false;
    _initializeTestSuites();
    
    state = state.copyWith(
      isRunning: true,
      completed: 0,
      currentPhase: "Preparing backup file tests",
      suiteStatuses: {
        for (var type in TestSuiteType.values) type: TestSuiteStatus.waiting
      },
    );
    _statusController.add(state);

    try {
      // Phase 1: Decrypt and parse backup file
      state = state.copyWith(currentPhase: "Decrypting backup file");
      _statusController.add(state);
      
      final decryptedJson = await _backupFileHandler!.decryptBackupFile(
        config.backupFilePath!,
        config.backupPassphrase!,
      );

      state = state.copyWith(currentPhase: "Parsing backup data");
      _statusController.add(state);
      
      final backupData = await _backupFileHandler!.parseBackupData(decryptedJson);
      final testableWallets = await _backupFileHandler!.getTestableWallets(backupData);

      if (testableWallets.isEmpty) {
        throw Exception("No testable wallets found in backup file");
      }

      // Phase 2: Set up test environment
      state = state.copyWith(currentPhase: "Setting up test environment");
      _statusController.add(state);
      
      final testDB = await _walletRestorationManager!.createTestDatabase();
      await _walletRestorationManager!.configureTestNodes(backupData.nodes);

      // Phase 3: Run tests with restored wallets
      state = state.copyWith(currentPhase: "Running backup file tests");
      _statusController.add(state);

      // Filter test suites to only run ones that have corresponding wallets in backup
      final availableCoinTypes = testableWallets.map((w) => w.coinName.toLowerCase()).toSet();
      final suitesToRun = TestSuiteType.values.where((type) {
        final coinName = _getCoinNameForTestSuite(type);
        return coinName != null && availableCoinTypes.contains(coinName.toLowerCase());
      }).toList();

      // Update total to reflect actual number of tests to run
      state = state.copyWith(total: suitesToRun.length);
      _statusController.add(state);

      for (final type in suitesToRun) {
        if (_cancelled) break;
        await runTestSuite(type);
      }

    } catch (e) {
      Logging.instance.log(Level.error, "Error running backup file tests: $e");
      state = state.copyWith(
        isRunning: false,
        currentPhase: "Error: ${e.toString()}",
      );
      _statusController.add(state);
    } finally {
      await _cleanupTestEnvironment();
      if (!_cancelled) {
        state = state.copyWith(
          isRunning: false,
          currentPhase: null,
        );
        _statusController.add(state);
      }
    }
  }

  /// Run programmed vector tests
  Future<void> runProgrammedVectorTests() async {
    final config = state.currentConfiguration;
    if (config == null || config.mode != TestingMode.programmedVectors) {
      throw Exception("Programmed vector testing mode not configured");
    }

    // Use the existing runAllTests implementation for programmed vectors
    await runAllTests();
  }

  TestSuiteInterface? getTestSuite(TestSuiteType type) {
    return _testSuites[type];
  }

  Widget getIconForTestSuite(TestSuiteType type, BuildContext context) {
    final colors = Theme.of(context).extension<StackColors>()!;
    
    switch (type) {
      case TestSuiteType.monero:
        return Icon(
          Icons.currency_bitcoin,
          size: 32,
          color: colors.accentColorOrange,
        );
      case TestSuiteType.wownero:
        return Icon(
          Icons.currency_bitcoin,
          size: 32,
          color: colors.accentColorBlue,
        );
      case TestSuiteType.salvium:
        return Icon(
          Icons.currency_bitcoin,
          size: 32,
          color: colors.accentColorBlue,
        );
      case TestSuiteType.epicCash:
        return Icon(
          Icons.currency_bitcoin,
          size: 32,
          color: colors.accentColorYellow,
        );
      case TestSuiteType.firo:
        return Icon(
          Icons.security,
          size: 32,
          color: colors.accentColorRed,
        );
      case TestSuiteType.litecoinMWEB:
        return Icon(
          Icons.currency_bitcoin,
          size: 32,
          color: colors.accentColorGreen,
        );
      case TestSuiteType.tor:
        return Icon(
          Icons.security,
          size: 32,
          color: colors.accentColorDark,
        );
      default:
        return Icon(
          Icons.help_outline,
          size: 32,
          color: colors.textDark,
        );
    }
  }

  String getDisplayNameForTestSuite(TestSuiteType type) {
    switch (type) {
      case TestSuiteType.monero:
        return "Monero";
      case TestSuiteType.wownero:
        return "Wownero";
      case TestSuiteType.salvium:
        return "Salvium";
      case TestSuiteType.epicCash:
        return "Epic Cash";
      case TestSuiteType.firo:
        return "Firo";
      case TestSuiteType.litecoinMWEB:
        return "Litecoin MWEB";
      case TestSuiteType.tor:
        return "Tor Service";
      default:
        return "Unknown";
    }
  }

  /// Helper method to get coin name for test suite type
  String? _getCoinNameForTestSuite(TestSuiteType type) {
    switch (type) {
      case TestSuiteType.monero:
        return "monero";
      case TestSuiteType.wownero:
        return "wownero";
      case TestSuiteType.salvium:
        return "salvium";
      case TestSuiteType.epicCash:
        return "epiccash";
      case TestSuiteType.firo:
        return "firo";
      case TestSuiteType.litecoinMWEB:
        return "litecoin";
      case TestSuiteType.tor:
        return null; // Tor is not a coin
    }
  }

  /// Clean up test environment
  Future<void> _cleanupTestEnvironment() async {
    try {
      if (_walletRestorationManager != null) {
        await _walletRestorationManager!.cleanup();
        _walletRestorationManager = null;
      }
      
      _backupFileHandler = null;
      _transactionTestExecutor = null;
      
      Logging.instance.log(Level.info, "Test environment cleanup completed");
    } catch (e) {
      Logging.instance.log(Level.error, "Error during test environment cleanup: $e");
    }
  }

  // Getters for accessing backup testing components
  BackupFileHandler? get backupFileHandler => _backupFileHandler;
  WalletRestorationManager? get walletRestorationManager => _walletRestorationManager;
  TransactionTestExecutor? get transactionTestExecutor => _transactionTestExecutor;

  @override
  void dispose() {
    _cleanupTestEnvironment();
    _statusController.close();
    super.dispose();
  }
}