/* 
 * This file is part of Stack Wallet.
 * 
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'dart:async';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:logger/logger.dart';

import '../../themes/stack_colors.dart';
import '../../utilities/logger.dart';
import 'testing_models.dart';
import 'test_suite_interface.dart';
import 'test_suites/monero_test_suite.dart';
import 'test_suites/wownero_test_suite.dart';
import 'test_suites/salvium_test_suite.dart';
import 'test_suites/epiccash_test_suite.dart';
import 'test_suites/firo_test_suite.dart';
import 'test_suites/litecoin_mweb_test_suite.dart';
import 'test_suites/tor_test_suite.dart';

final testingServiceProvider = StateNotifierProvider<TestingService, TestingSessionState>((ref) {
  return TestingService();
});

class TestingService extends StateNotifier<TestingSessionState> {
  TestingService() : super(TestingSessionState(
    suiteStatuses: {
      for (var type in TestSuiteType.values) type: TestSuiteStatus.waiting
    },
    isRunning: false,
    completed: 0,
    total: TestSuiteType.values.length,
  ));

  final Map<TestSuiteType, TestSuiteInterface> _testSuites = {};
  final StreamController<TestingSessionState> _statusController = StreamController<TestingSessionState>.broadcast();
  bool _cancelled = false;

  Stream<TestingSessionState> get statusStream => _statusController.stream;

  void _initializeTestSuites() {
    _testSuites[TestSuiteType.monero] = MoneroTestSuite();
    _testSuites[TestSuiteType.wownero] = WowneroTestSuite();
    _testSuites[TestSuiteType.salvium] = SalviumTestSuite();
    _testSuites[TestSuiteType.epicCash] = EpicCashTestSuite();
    _testSuites[TestSuiteType.firo] = FiroTestSuite();
    _testSuites[TestSuiteType.litecoinMWEB] = LitecoinMWEBTestSuite();
    _testSuites[TestSuiteType.tor] = TorTestSuite();
  }

  Future<void> runAllTests() async {
    if (state.isRunning) return;
    
    _cancelled = false;
    _initializeTestSuites();
    
    state = state.copyWith(
      isRunning: true,
      completed: 0,
      suiteStatuses: {
        for (var type in TestSuiteType.values) type: TestSuiteStatus.waiting
      },
    );
    _statusController.add(state);

    try {
      for (final type in TestSuiteType.values) {
        if (_cancelled) break;

        await runTestSuite(type);
      }
    } catch (e) {
      Logging.instance.log(Level.error, "Error running test suites: $e");
    } finally {
      state = state.copyWith(isRunning: false);
      _statusController.add(state);
    }
  }

  Future<void> runTestSuite(TestSuiteType type) async {
    if (_cancelled) return;

    final suite = _testSuites[type];
    if (suite == null) return;

    final updatedStatuses = Map<TestSuiteType, TestSuiteStatus>.from(state.suiteStatuses);
    updatedStatuses[type] = TestSuiteStatus.running;
    
    state = state.copyWith(suiteStatuses: updatedStatuses);
    _statusController.add(state);

    try {
      final result = await suite.runTests().timeout(
        const Duration(seconds: 30),
        onTimeout: () => const TestResult(
          success: false,
          message: "Test suite timed out",
          logs: ["Test execution exceeded 30 second timeout"],
          executionTime: Duration(seconds: 30),
        ),
      );

      if (_cancelled) return;

      updatedStatuses[type] = result.success ? TestSuiteStatus.passed : TestSuiteStatus.failed;
      
      final completed = updatedStatuses.values
          .where((status) => status == TestSuiteStatus.passed || status == TestSuiteStatus.failed)
          .length;

      state = state.copyWith(
        suiteStatuses: updatedStatuses,
        completed: completed,
      );
      _statusController.add(state);

      await suite.cleanup();
    } catch (e) {
      if (_cancelled) return;

      updatedStatuses[type] = TestSuiteStatus.failed;
      
      final completed = updatedStatuses.values
          .where((status) => status == TestSuiteStatus.passed || status == TestSuiteStatus.failed)
          .length;

      state = state.copyWith(
        suiteStatuses: updatedStatuses,
        completed: completed,
      );
      _statusController.add(state);

      Logging.instance.log(Level.error, "Error running $type test suite: $e");
    }
  }

  Future<void> cancelTesting() async {
    _cancelled = true;
    state = state.copyWith(isRunning: false);
    _statusController.add(state);
    
    for (final suite in _testSuites.values) {
      await suite.cleanup();
    }
  }

  Future<void> resetTestResults() async {
    state = TestingSessionState(
      suiteStatuses: {
        for (var type in TestSuiteType.values) type: TestSuiteStatus.waiting
      },
      isRunning: false,
      completed: 0,
      total: TestSuiteType.values.length,
    );
    _statusController.add(state);
  }

  TestSuiteInterface? getTestSuite(TestSuiteType type) {
    return _testSuites[type];
  }

  Widget getIconForTestSuite(TestSuiteType type, BuildContext context) {
    final colors = Theme.of(context).extension<StackColors>()!;
    
    switch (type) {
      case TestSuiteType.monero:
        return Icon(
          Icons.currency_bitcoin,
          size: 32,
          color: colors.accentColorOrange,
        );
      case TestSuiteType.wownero:
        return Icon(
          Icons.currency_bitcoin,
          size: 32,
          color: colors.accentColorBlue,
        );
      case TestSuiteType.salvium:
        return Icon(
          Icons.currency_bitcoin,
          size: 32,
          color: colors.accentColorBlue,
        );
      case TestSuiteType.epicCash:
        return Icon(
          Icons.currency_bitcoin,
          size: 32,
          color: colors.accentColorYellow,
        );
      case TestSuiteType.firo:
        return Icon(
          Icons.security,
          size: 32,
          color: colors.accentColorRed,
        );
      case TestSuiteType.litecoinMWEB:
        return Icon(
          Icons.currency_bitcoin,
          size: 32,
          color: colors.accentColorGreen,
        );
      case TestSuiteType.tor:
        return Icon(
          Icons.security,
          size: 32,
          color: colors.accentColorDark,
        );
      default:
        return Icon(
          Icons.help_outline,
          size: 32,
          color: colors.textDark,
        );
    }
  }

  String getDisplayNameForTestSuite(TestSuiteType type) {
    switch (type) {
      case TestSuiteType.monero:
        return "Monero";
      case TestSuiteType.wownero:
        return "Wownero";
      case TestSuiteType.salvium:
        return "Salvium";
      case TestSuiteType.epicCash:
        return "Epic Cash";
      case TestSuiteType.firo:
        return "Firo";
      case TestSuiteType.litecoinMWEB:
        return "Litecoin MWEB";
      case TestSuiteType.tor:
        return "Tor Service";
      default:
        return "Unknown";
    }
  }

  @override
  void dispose() {
    _statusController.close();
    super.dispose();
  }
}