/* 
 * This file is part of Stack Wallet.
 * 
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */


enum TestSuiteStatus { waiting, running, passed, failed }

enum TestSuiteType { 
  monero, 
  wownero, 
  salvium, 
  epicCash, 
  firo, 
  litecoinMWEB, 
  tor 
}

class TestResult {
  final bool success;
  final String message;
  final List<String> logs;
  final Duration executionTime;

  const TestResult({
    required this.success,
    required this.message,
    required this.logs,
    required this.executionTime,
  });
}

class TestingSessionState {
  final Map<TestSuiteType, TestSuiteStatus> suiteStatuses;
  final bool isRunning;
  final int completed;
  final int total;

  const TestingSessionState({
    required this.suiteStatuses,
    required this.isRunning,
    required this.completed,
    required this.total,
  });

  TestingSessionState copyWith({
    Map<TestSuiteType, TestSuiteStatus>? suiteStatuses,
    bool? isRunning,
    int? completed,
    int? total,
  }) {
    return TestingSessionState(
      suiteStatuses: suiteStatuses ?? this.suiteStatuses,
      isRunning: isRunning ?? this.isRunning,
      completed: completed ?? this.completed,
      total: total ?? this.total,
    );
  }
}