/* 
 * This file is part of Stack Wallet.
 * 
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

class BitcoinTestVectors {
  static const List<TestVector> basicVectors = [
    TestVector(
      name: "Bitcoin Wallet Creation",
      mnemonic: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about",
      coinName: "bitcoin",
      expectedAddresses: [
        // P2PKH addresses
        "1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2",
        "1KXrWXciRDZUpQwQmuM1DbwsKDLYAYsVLR",
      ],
      expectedPrivateKeys: [
        "L53fCHmQhbNp1B4JipfBtfeHZH7cAibzG9oK19XfiFzxHgAkz6JK",
      ],
    ),
    TestVector(
      name: "Bitcoin Testnet Wallet",
      mnemonic: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about",
      coinName: "bitcoin_testnet",
      expectedAddresses: [
        "mkHS9ne12qx9pS9VojpwU5xtRd4T7X7ZUt",
        "mgh7XEHFHUzq6bHZtyHPJRJFLJUEv9GZyr",
      ],
      expectedPrivateKeys: [
        "cP53pDbR5WtAD8dYAW9hhTjuvvTVaEiQBdrz9XPrgLBeRFiyCbQr",
      ],
    ),
  ];

  static const List<TestVector> transactionVectors = [
    TestVector(
      name: "Bitcoin Simple Transaction",
      mnemonic: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about",
      coinName: "bitcoin",
      transactionData: {
        "inputs": [
          {
            "txid": "d5d9b75eb86ac9b2e3dd99c7d4b7fe16acbc1ac4f21a3e8f5e7c9f7e4a8b5c3d",
            "vout": 0,
            "value": 100000000, // 1 BTC in satoshis
          }
        ],
        "outputs": [
          {
            "address": "1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2",
            "value": 50000000, // 0.5 BTC
          }
        ],
        "expectedFee": 1000, // 1000 sats
      },
    ),
  ];

  static const List<TestVector> addressGenerationVectors = [
    TestVector(
      name: "Bitcoin Address Derivation Path m/44'/0'/0'/0/0",
      mnemonic: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about",
      coinName: "bitcoin",
      derivationPath: "m/44'/0'/0'/0/0",
      expectedAddresses: ["1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2"],
    ),
    TestVector(
      name: "Bitcoin Address Derivation Path m/44'/0'/0'/0/1",
      mnemonic: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about",
      coinName: "bitcoin",
      derivationPath: "m/44'/0'/0'/0/1",
      expectedAddresses: ["1KXrWXciRDZUpQwQmuM1DbwsKDLYAYsVLR"],
    ),
  ];
}

class MoneroTestVectors {
  static const List<TestVector> basicVectors = [
    TestVector(
      name: "Monero Wallet Creation",
      mnemonic: "sequence atlas unveil summon pebbles tuesday beer rudely snake rockets different fuselage woven tagged bested dented vegan hover rapid fawns obvious muppet randomly seasons randomly",
      coinName: "monero",
      expectedAddresses: [
        "42ey1afDFnn4886T7196doS9GPMzexD9gXpsZJDwVjeRVdFCSoHnv7KPbBeGpzJBzHRCAs9UxqeoyFQMYbqSWYTfJJQAWDm",
      ],
    ),
  ];

  static const List<TestVector> addressGenerationVectors = [
    TestVector(
      name: "Monero Primary Address",
      mnemonic: "sequence atlas unveil summon pebbles tuesday beer rudely snake rockets different fuselage woven tagged bested dented vegan hover rapid fawns obvious muppet randomly seasons randomly",
      coinName: "monero",
      expectedAddresses: [
        "42ey1afDFnn4886T7196doS9GPMzexD9gXpsZJDwVjeRVdFCSoHnv7KPbBeGpzJBzHRCAs9UxqeoyFQMYbqSWYTfJJQAWDm",
      ],
    ),
  ];
}

class EthereumTestVectors {
  static const List<TestVector> basicVectors = [
    TestVector(
      name: "Ethereum Wallet Creation",
      mnemonic: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about",
      coinName: "ethereum",
      expectedAddresses: [
        "0x9858EfFD232B4033E47d90003D41EC34EcaEda94",
        "0x6Fac4D18c912343BF86fa7049364Dd4E424Ab9C0",
      ],
      expectedPrivateKeys: [
        "0x4f3edf983ac636a65a842ce7c78d9aa706d3b113bce9c46f30d7d21715b23b1d",
      ],
    ),
  ];

  static const List<TestVector> transactionVectors = [
    TestVector(
      name: "Ethereum Simple Transfer",
      mnemonic: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about",
      coinName: "ethereum",
      transactionData: {
        "to": "0x6Fac4D18c912343BF86fa7049364Dd4E424Ab9C0",
        "value": "1000000000000000000", // 1 ETH in wei
        "gasPrice": "20000000000", // 20 gwei
        "gasLimit": "21000",
        "expectedFee": "420000000000000", // 21000 * 20 gwei
      },
    ),
  ];
}

class TestVector {
  final String name;
  final String mnemonic;
  final String coinName;
  final List<String> expectedAddresses;
  final List<String> expectedPrivateKeys;
  final String? derivationPath;
  final Map<String, dynamic>? transactionData;

  const TestVector({
    required this.name,
    required this.mnemonic,
    required this.coinName,
    required this.expectedAddresses,
    this.expectedPrivateKeys = const [],
    this.derivationPath,
    this.transactionData,
  });
}

class TestVectorUtils {
  /// Gets test vectors for a specific coin
  static List<TestVector> getVectorsForCoin(String coinName) {
    switch (coinName.toLowerCase()) {
      case 'bitcoin':
        return BitcoinTestVectors.basicVectors;
      case 'monero':
        return MoneroTestVectors.basicVectors;
      case 'ethereum':
        return EthereumTestVectors.basicVectors;
      default:
        return [];
    }
  }

  /// Gets transaction test vectors for a specific coin
  static List<TestVector> getTransactionVectorsForCoin(String coinName) {
    switch (coinName.toLowerCase()) {
      case 'bitcoin':
        return BitcoinTestVectors.transactionVectors;
      case 'ethereum':
        return EthereumTestVectors.transactionVectors;
      default:
        return [];
    }
  }

  /// Gets address generation test vectors for a specific coin
  static List<TestVector> getAddressVectorsForCoin(String coinName) {
    switch (coinName.toLowerCase()) {
      case 'bitcoin':
        return BitcoinTestVectors.addressGenerationVectors;
      case 'monero':
        return MoneroTestVectors.addressGenerationVectors;
      default:
        return [];
    }
  }

  /// Validates a test vector against expected results
  static bool validateTestVector(TestVector vector, Map<String, dynamic> actualResults) {
    // Validate addresses
    if (vector.expectedAddresses.isNotEmpty) {
      final actualAddresses = actualResults['addresses'] as List<String>? ?? [];
      for (final expectedAddress in vector.expectedAddresses) {
        if (!actualAddresses.contains(expectedAddress)) {
          return false;
        }
      }
    }

    // Validate private keys
    if (vector.expectedPrivateKeys.isNotEmpty) {
      final actualKeys = actualResults['privateKeys'] as List<String>? ?? [];
      for (final expectedKey in vector.expectedPrivateKeys) {
        if (!actualKeys.contains(expectedKey)) {
          return false;
        }
      }
    }

    // Validate transaction data
    if (vector.transactionData != null) {
      final actualTxData = actualResults['transaction'] as Map<String, dynamic>?;
      if (actualTxData == null) {
        return false;
      }

      // Add specific transaction validation logic here
      // This would depend on the coin type and transaction structure
    }

    return true;
  }
}