/* 
 * This file is part of Stack Wallet.
 * 
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

class DashTestVectors {
  static const List<TestVector> basicVectors = [
    TestVector(
      name: "Dash Wallet Creation",
      mnemonic: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about",
      coinName: "dash",
      expectedAddresses: [
        // Dash mainnet addresses start with 'X'
        "XdMqDErxVYq7qKqkMnDT4VYyYNjNJjBRmJ",
        "XkG1QMYhGKYLNqwvANxKRbfEqPiE7sJ8Mn", 
      ],
      expectedPrivateKeys: [
        "XFgDz8WzCHJKxHKKVgL5bWzDu2RvP4wZjT7Jk1M3Qx2sVn9Lc8Wr",
      ],
    ),
  ];

  static const List<TestVector> instantSendVectors = [
    TestVector(
      name: "InstantSend Transaction",
      mnemonic: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about",
      coinName: "dash",
      transactionData: {
        "type": "instantsend",
        "inputs": [
          {
            "txid": "a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a7b8c9d0e1f2",
            "vout": 0,
            "value": 100000000, // 1 DASH in duffs
            "address": "XdMqDErxVYq7qKqkMnDT4VYyYNjNJjBRmJ"
          }
        ],
        "outputs": [
          {
            "address": "XkG1QMYhGKYLNqwvANxKRbfEqPiE7sJ8Mn",
            "value": 99990000, // 0.9999 DASH (minus fee)
          }
        ],
        "features": {
          "instantsend": true,
          "lockTime": 0,
          "masternodeQuorum": "llmq_50_60"
        }
      },
    ),
  ];

  static const List<TestVector> privateSendVectors = [
    TestVector(
      name: "PrivateSend Mixing",
      mnemonic: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about",
      coinName: "dash",
      transactionData: {
        "type": "privatesend",
        "denomination": "0.1", // Standard PrivateSend denomination
        "mixingRounds": 2,
        "inputs": [
          {
            "txid": "b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a7b8c9d0e1f2g3",
            "vout": 0,
            "value": 10000000, // 0.1 DASH in duffs
            "denomination": true
          }
        ],
        "outputs": [
          {
            "value": 10000000, // 0.1 DASH denomination
            "mixed": true,
            "rounds": 2
          }
        ],
        "features": {
          "privatesend": true,
          "mixing": true,
          "denomination": "0.1"
        }
      },
    ),
  ];

  static const List<TestVector> masternodeVectors = [
    TestVector(
      name: "Masternode Network Validation",
      mnemonic: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about",
      coinName: "dash",
      masternodeData: {
        "totalMasternodes": 4500,
        "enabledMasternodes": 4450,
        "services": [
          "instantsend",
          "privatesend", 
          "chainlocks",
          "llmq_validation"
        ],
        "quorums": {
          "llmq_50_60": {
            "size": 50,
            "threshold": 30,
            "active": true
          },
          "llmq_400_60": {
            "size": 400,
            "threshold": 240, 
            "active": true
          }
        }
      },
    ),
  ];

  static const List<TestVector> x11AlgorithmVectors = [
    TestVector(
      name: "X11 Algorithm Validation",
      coinName: "dash",
      algorithmData: {
        "algorithm": "x11",
        "hashFunctions": [
          "blake",
          "bmw",
          "groestl", 
          "jh",
          "keccak",
          "skein",
          "luffa",
          "cubehash",
          "shavite3",
          "simd",
          "echo"
        ],
        "blockTime": 150, // 2.5 minutes in seconds
        "difficulty": {
          "adjustment": "every_block",
          "algorithm": "dark_gravity_wave"
        }
      },
    ),
  ];

  static const List<TestVector> chainLocksVectors = [
    TestVector(
      name: "ChainLocks Validation", 
      coinName: "dash",
      chainLocksData: {
        "enabled": true,
        "quorum": "llmq_400_60",
        "signatures": {
          "required": 240,
          "validation": "bls12_381"
        },
        "protection": [
          "51_percent_attack",
          "selfish_mining",
          "reorganization_attack"
        ]
      },
    ),
  ];
}

class TestVector {
  final String name;
  final String? mnemonic;
  final String coinName;
  final List<String>? expectedAddresses;
  final List<String>? expectedPrivateKeys;
  final Map<String, dynamic>? transactionData;
  final Map<String, dynamic>? masternodeData;
  final Map<String, dynamic>? algorithmData;
  final Map<String, dynamic>? chainLocksData;

  const TestVector({
    required this.name,
    this.mnemonic,
    required this.coinName,
    this.expectedAddresses,
    this.expectedPrivateKeys,
    this.transactionData,
    this.masternodeData,
    this.algorithmData,
    this.chainLocksData,
  });
}