/* 
 * This file is part of Stack Wallet.
 * 
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

class LitecoinTestVectors {
  static const List<TestVector> basicVectors = [
    TestVector(
      name: "Litecoin Wallet Creation",
      mnemonic: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about",
      coinName: "litecoin",
      expectedAddresses: [
        // Litecoin legacy addresses start with 'L'
        "LhK2KvuCtdMfbGCt3pqRRoFU4lKxJgQF8e",
        "LfJGu5sJeE3LYJdGm8DrZfKqo2GQHdNp7B",
      ],
      expectedPrivateKeys: [
        "T9rZv4nMxnbhgGhKpJLe8vPzKwL5tJ2QdF1sNzWxU8yHr3Vt6M4C",
      ],
    ),
    TestVector(
      name: "Litecoin SegWit Addresses",
      mnemonic: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about",
      coinName: "litecoin",
      addressType: "segwit",
      expectedAddresses: [
        // P2SH-wrapped SegWit addresses start with '3'
        "3J8R7nj2hVRhFBQhJo2T5FGZiZ8UWM4k9X",
        "3NLpQZGzX9VfDGFKkJ5Q8YnR1LzJhWs2tF",
      ],
    ),
    TestVector(
      name: "Litecoin Native SegWit Addresses",
      mnemonic: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about",
      coinName: "litecoin",
      addressType: "native_segwit",
      expectedAddresses: [
        // Native SegWit addresses start with 'ltc1'
        "ltc1qw508d6qejxtdg4y5r3zarvary0c5xw7kv8f3t4",
        "ltc1qrp33g5q4v6n0xagsxfnx94nqe3ejhmqhk4c5x2",
      ],
    ),
  ];

  static const List<TestVector> transactionVectors = [
    TestVector(
      name: "Litecoin Standard Transaction",
      mnemonic: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about",
      coinName: "litecoin",
      transactionData: {
        "inputs": [
          {
            "txid": "c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2",
            "vout": 0,
            "value": 100000000, // 1 LTC in litoshis
            "address": "LhK2KvuCtdMfbGCt3pqRRoFU4lKxJgQF8e"
          }
        ],
        "outputs": [
          {
            "address": "LfJGu5sJeE3LYJdGm8DrZfKqo2GQHdNp7B",
            "value": 99990000, // 0.9999 LTC (minus fee)
          }
        ],
        "fee": 10000, // 0.0001 LTC fee
        "feeRate": 1 // 1 litoshi per byte
      },
    ),
  ];

  static const List<TestVector> segwitVectors = [
    TestVector(
      name: "Litecoin SegWit Transaction",
      mnemonic: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about",
      coinName: "litecoin",
      transactionData: {
        "type": "segwit",
        "inputs": [
          {
            "txid": "d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3",
            "vout": 0,
            "value": 50000000, // 0.5 LTC in litoshis
            "address": "3J8R7nj2hVRhFBQhJo2T5FGZiZ8UWM4k9X",
            "scriptType": "p2sh_segwit"
          }
        ],
        "outputs": [
          {
            "address": "ltc1qw508d6qejxtdg4y5r3zarvary0c5xw7kv8f3t4",
            "value": 49992500, // ~0.499925 LTC (minus fee)
            "scriptType": "native_segwit"
          }
        ],
        "fee": 7500, // 0.000075 LTC (25% discount for SegWit)
        "feeRate": 1,
        "witness": true
      },
    ),
  ];

  static const List<TestVector> scryptVectors = [
    TestVector(
      name: "Scrypt Algorithm Validation",
      coinName: "litecoin",
      algorithmData: {
        "algorithm": "scrypt",
        "parameters": {
          "N": 1024,          // Iterations
          "r": 1,             // Memory factor
          "p": 1,             // Parallelization
          "dkLen": 32         // Output length in bytes
        },
        "blockTime": 150,     // 2.5 minutes in seconds
        "difficulty": {
          "adjustment": "every_2016_blocks",
          "timespan": 302400  // 2016 blocks * 150 seconds
        },
        "properties": [
          "memory_hard",
          "asic_resistant",
          "gpu_friendly"
        ]
      },
    ),
  ];

  static const List<TestVector> blockchainVectors = [
    TestVector(
      name: "Litecoin Blockchain Parameters",
      coinName: "litecoin",
      blockchainData: {
        "blockTime": 150,                    // 2.5 minutes
        "blocksPerDay": 576,                // 24 * 60 / 2.5
        "difficultyAdjustment": 2016,       // blocks
        "halvingInterval": 840000,          // blocks (~4 years)
        "maxSupply": 84000000,              // 84 million LTC
        "genesisBlock": {
          "hash": "12a765e31ffd4059bada1e25190f6e98c99d9714d334efa41a195a7e7e04bfe2",
          "timestamp": 1317972665,
          "nonce": 2084524493
        }
      },
    ),
  ];

  static const List<TestVector> feeVectors = [
    TestVector(
      name: "Litecoin Fee Calculation",
      coinName: "litecoin",
      feeData: {
        "baseUnit": "litoshi",              // Smallest unit
        "satPerByte": {
          "slow": 1,                        // 1 litoshi/byte
          "normal": 2,                      // 2 litoshis/byte  
          "fast": 5,                        // 5 litoshis/byte
          "priority": 10                    // 10 litoshis/byte
        },
        "segwitDiscount": 0.25,             // 25% discount
        "typicalSizes": {
          "legacy_p2pkh": 226,              // bytes
          "segwit_p2sh": 169,               // bytes (with discount)
          "native_segwit": 141              // bytes (with discount)
        }
      },
    ),
  ];
}

class TestVector {
  final String name;
  final String? mnemonic;
  final String coinName;
  final String? addressType;
  final List<String>? expectedAddresses;
  final List<String>? expectedPrivateKeys;
  final Map<String, dynamic>? transactionData;
  final Map<String, dynamic>? algorithmData;
  final Map<String, dynamic>? blockchainData;
  final Map<String, dynamic>? feeData;

  const TestVector({
    required this.name,
    this.mnemonic,
    required this.coinName,
    this.addressType,
    this.expectedAddresses,
    this.expectedPrivateKeys,
    this.transactionData,
    this.algorithmData,
    this.blockchainData,
    this.feeData,
  });
}