/* 
 * This file is part of Stack Wallet.
 * 
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

class TestVector {
  final String name;
  final String? mnemonic;
  final String coinName;
  final List<String>? expectedAddresses;
  final List<String>? expectedPrivateKeys;
  final Map<String, dynamic>? transactionData;
  final Map<String, dynamic>? domainData;
  final Map<String, dynamic>? nameUpdateData;
  final Map<String, dynamic>? transferData;

  const TestVector({
    required this.name,
    this.mnemonic,
    required this.coinName,
    this.expectedAddresses,
    this.expectedPrivateKeys,
    this.transactionData,
    this.domainData,
    this.nameUpdateData,
    this.transferData,
  });
}

class NamecoinTestVectors {
  static const List<TestVector> basicVectors = [
    TestVector(
      name: "Namecoin Wallet Creation",
      mnemonic: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about",
      coinName: "namecoin",
      expectedAddresses: [
        // Namecoin addresses start with N or 3
        "NEYzs3GhQmj8hBdLt5pZH7yWQKKT7dSjVz",
        "NKuyRd7LmYs4SdLG6oiFTFPcKpNw2ZZNh7",
      ],
      expectedPrivateKeys: [
        "L53fCHmQhbNp1B4JipfBtfeHZH7cAibzG9oK19XfiFzxHgAkz6JK",
      ],
    ),
    TestVector(
      name: "Namecoin Domain Registration",
      mnemonic: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about",
      coinName: "namecoin",
      domainData: {
        "domainName": "d/example",
        "dnsRecords": {
          "": {
            "ip": "192.168.1.1",
            "ns": ["ns1.example.bit", "ns2.example.bit"]
          }
        },
        "registrationCost": 50000000, // 0.5 NMC in satoshis
        "commitPhase": {
          "operation": "name_new",
          "hash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
        },
        "revealPhase": {
          "operation": "name_firstupdate",
          "name": "d/example",
          "value": "{\"ip\":\"192.168.1.1\"}",
        }
      },
    ),
  ];

  static const List<TestVector> domainVectors = [
    TestVector(
      name: "Domain Name Registration Transaction",
      mnemonic: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about",
      coinName: "namecoin",
      transactionData: {
        "type": "name_new",
        "inputs": [
          {
            "txid": "d5d9b75eb86ac9b2e3dd99c7d4b7fe16acbc1ac4f21a3e8f5e7c9f7e4a8b5c3d",
            "vout": 0,
            "value": 100000000, // 1 NMC in satoshis
          }
        ],
        "outputs": [
          {
            "address": "NEYzs3GhQmj8hBdLt5pZH7yWQKKT7dSjVz",
            "value": 49990000, // 1 NMC minus registration fee
          }
        ],
        "nameData": {
          "operation": "name_new",
          "hash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
        },
        "expectedFee": 10000, // 0.0001 NMC
      },
    ),
    TestVector(
      name: "Domain Name Update Transaction",
      coinName: "namecoin",
      nameUpdateData: {
        "operation": "name_update",
        "name": "d/example",
        "newValue": "{\"ip\":\"192.168.1.100\",\"ns\":[\"ns1.example.bit\"]}",
        "currentOwner": "NEYzs3GhQmj8hBdLt5pZH7yWQKKT7dSjVz",
        "updateFee": 5000, // Update fee in satoshis
      },
    ),
  ];

  static const List<TestVector> transferVectors = [
    TestVector(
      name: "Domain Name Transfer Transaction",
      coinName: "namecoin",
      transferData: {
        "operation": "name_update",
        "name": "d/example", 
        "currentOwner": "NEYzs3GhQmj8hBdLt5pZH7yWQKKT7dSjVz",
        "newOwner": "NKuyRd7LmYs4SdLG6oiFTFPcKpNw2ZZNh7",
        "transferValue": "{\"transfer\":true,\"ip\":\"192.168.1.100\"}",
        "transferFee": 5000,
      },
    ),
  ];

  static const List<TestVector> dnsVectors = [
    TestVector(
      name: "DNS Record Parsing",
      coinName: "namecoin",
      domainData: {
        "name": "d/example",
        "value": '''
        {
          "": {
            "ip": "192.168.1.1",
            "ns": ["ns1.example.bit", "ns2.example.bit"]
          },
          "www": {
            "ip": "192.168.1.2"
          },
          "mail": {
            "ip": "192.168.1.3",
            "mx": [{"host": "mail.example.bit", "priority": 10}]
          }
        }
        ''',
        "expectedRecords": {
          "A": [{"name": "example.bit", "value": "192.168.1.1"}],
          "NS": [
            {"name": "example.bit", "value": "ns1.example.bit"},
            {"name": "example.bit", "value": "ns2.example.bit"}
          ],
          "CNAME": [{"name": "www.example.bit", "value": "192.168.1.2"}],
          "MX": [{"name": "mail.example.bit", "value": "mail.example.bit", "priority": 10}]
        }
      },
    ),
  ];
}

class NamecoinTestVectorUtils {
  /// Gets test vectors for Namecoin operations
  static List<TestVector> getVectorsForOperation(String operation) {
    switch (operation.toLowerCase()) {
      case 'basic':
        return NamecoinTestVectors.basicVectors;
      case 'domain':
        return NamecoinTestVectors.domainVectors;
      case 'transfer':
        return NamecoinTestVectors.transferVectors;
      case 'dns':
        return NamecoinTestVectors.dnsVectors;
      default:
        return NamecoinTestVectors.basicVectors;
    }
  }

  /// Gets domain registration test vectors
  static List<TestVector> getDomainVectors() {
    return NamecoinTestVectors.domainVectors;
  }

  /// Gets DNS parsing test vectors
  static List<TestVector> getDnsVectors() {
    return NamecoinTestVectors.dnsVectors;
  }

  /// Gets name transfer test vectors
  static List<TestVector> getTransferVectors() {
    return NamecoinTestVectors.transferVectors;
  }

  /// Validates domain name format (.bit domains)
  static bool validateDomainName(String name) {
    // Namecoin domain names should start with d/ for domains
    if (!name.startsWith('d/')) return false;
    
    // Extract the actual domain name
    final domain = name.substring(2);
    
    // Basic validation - should not be empty and should be valid domain format
    if (domain.isEmpty) return false;
    
    // Should not contain invalid characters
    final validPattern = RegExp(r'^[a-zA-Z0-9\-\.]+$');
    return validPattern.hasMatch(domain);
  }

  /// Validates DNS record format
  static bool validateDnsRecord(String record) {
    try {
      // Should be valid JSON
      final Map<String, dynamic> parsed = {};
      // Simplified validation - in real implementation would parse JSON
      return record.contains('{') && record.contains('}');
    } catch (e) {
      return false;
    }
  }

  /// Calculates domain registration cost
  static int calculateRegistrationCost(String domainName) {
    // Namecoin domain registration base cost (0.01 NMC)
    const baseCost = 1000000; // 0.01 NMC in satoshis
    
    // Short domains cost more
    final domain = domainName.startsWith('d/') ? domainName.substring(2) : domainName;
    if (domain.length <= 3) {
      return baseCost * 100; // 1 NMC for very short domains
    } else if (domain.length <= 6) {
      return baseCost * 10; // 0.1 NMC for short domains
    }
    
    return baseCost; // 0.01 NMC for normal domains
  }
}