/* 
 * This file is part of Stack Wallet.
 * 
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

class TestVector {
  final String name;
  final String? mnemonic;
  final String coinName;
  final List<String>? expectedAddresses;
  final List<String>? expectedPrivateKeys;
  final Map<String, dynamic>? transactionData;
  final Map<String, dynamic>? privacyData;
  final Map<String, dynamic>? marketplaceData;
  final Map<String, dynamic>? stakingData;
  final Map<String, dynamic>? governanceData;

  const TestVector({
    required this.name,
    this.mnemonic,
    required this.coinName,
    this.expectedAddresses,
    this.expectedPrivateKeys,
    this.transactionData,
    this.privacyData,
    this.marketplaceData,
    this.stakingData,
    this.governanceData,
  });
}

class ParticlTestVectors {
  static const List<TestVector> basicVectors = [
    TestVector(
      name: "Particl Wallet Creation",
      mnemonic: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about",
      coinName: "particl",
      expectedAddresses: [
        // Particl public addresses start with P
        "PZdSzPG6FzQ5cXsQGdYTTu7DhALxg8bG8s",
        "Pb1FHBi8G5nD2y7EdH9jU4Af3vFZMkN6tK",
        // Particl stealth addresses start with S  
        "Sx1FHBi8G5nD2y7EdH9jU4Af3vFZMkN6tKabc123",
      ],
      expectedPrivateKeys: [
        "L53fCHmQhbNp1B4JipfBtfeHZH7cAibzG9oK19XfiFzxHgAkz6JK",
      ],
    ),
    TestVector(
      name: "Particl Privacy Features",
      mnemonic: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about",
      coinName: "particl",
      privacyData: {
        "ringctTransaction": {
          "inputAmount": 100000000, // 1 PART
          "outputAmount": 90000000,  // 0.9 PART (minus fee)
          "fee": 10000000,           // 0.1 PART fee
          "ringSize": 11,            // Particl uses ring size 11
          "stealthAddress": "Sx1FHBi8G5nD2y7EdH9jU4Af3vFZMkN6tKabc123",
        },
        "blindTransaction": {
          "type": "blind",
          "commitmentAmount": true,
          "blindingFactor": "a3b4c5d6e7f8901234567890abcdef123456789012345678901234567890abcd",
          "rangeProof": true,
        }
      },
    ),
  ];

  static const List<TestVector> marketplaceVectors = [
    TestVector(
      name: "Marketplace Product Listing",
      coinName: "particl",
      marketplaceData: {
        "listing": {
          "title": "Test Product",
          "description": "A test product for marketplace testing",
          "price": 50000000, // 0.5 PART
          "category": "electronics",
          "images": ["hash1", "hash2"],
          "escrowType": "mad", // Mutually Assured Destruction
          "shippingCost": 5000000, // 0.05 PART
        },
        "escrow": {
          "buyerDeposit": 100000000,  // 1 PART
          "sellerDeposit": 100000000, // 1 PART  
          "totalEscrow": 200000000,   // 2 PART total
          "releaseCondition": "mutual_consent",
        },
        "messaging": {
          "encryptionType": "end_to_end",
          "protocol": "smsg", // Secure messaging protocol
          "ttl": 172800,      // 48 hours
        }
      },
    ),
    TestVector(
      name: "Marketplace Order Flow",
      coinName: "particl",
      marketplaceData: {
        "order": {
          "listingId": "abc123def456",
          "quantity": 1,
          "totalPrice": 55000000, // 0.55 PART (product + shipping)
          "buyerAddress": "PZdSzPG6FzQ5cXsQGdYTTu7DhALxg8bG8s",
          "sellerAddress": "Pb1FHBi8G5nD2y7EdH9jU4Af3vFZMkN6tK",
        },
        "fulfillment": {
          "status": "pending",
          "trackingNumber": null,
          "deliveryConfirmation": false,
          "disputeDeadline": 1234567890, // Unix timestamp
        }
      },
    ),
  ];

  static const List<TestVector> stakingVectors = [
    TestVector(
      name: "Cold Staking Configuration", 
      coinName: "particl",
      stakingData: {
        "coldStaking": {
          "stakingAddress": "PZdSzPG6FzQ5cXsQGdYTTu7DhALxg8bG8s",
          "spendAddress": "Pb1FHBi8G5nD2y7EdH9jU4Af3vFZMkN6tK",
          "poolAddress": "Pc1FHBi8G5nD2y7EdH9jU4Af3vFZMkN6tL",
          "delegatedAmount": 1000000000, // 10 PART
          "expectedReward": 50000000,    // ~5% annually
        },
        "staking": {
          "minimumStake": 100000000,     // 1 PART minimum
          "maturityTime": 8640,          // 8640 blocks (about 24 hours)
          "averageBlockTime": 120,       // 2 minutes per block
          "stakingWeight": 1000000000,   // 10 PART weight
        }
      },
    ),
  ];

  static const List<TestVector> governanceVectors = [
    TestVector(
      name: "Governance Proposal",
      coinName: "particl",
      governanceData: {
        "proposal": {
          "title": "Test Governance Proposal",
          "description": "A test proposal for governance system testing",
          "requestedAmount": 100000000000, // 1000 PART
          "votingPeriod": 10080,           // 1 week in blocks
          "minimumQuorum": 20,             // 20% participation required
          "passingThreshold": 51,          // 51% yes votes required
        },
        "voting": {
          "voterAddress": "PZdSzPG6FzQ5cXsQGdYTTu7DhALxg8bG8s",
          "votingWeight": 1000000000,      // Based on PART holdings
          "vote": "yes",                   // yes/no/abstain
          "lockPeriod": 10080,             // Funds locked during voting
        }
      },
    ),
  ];

  static const List<TestVector> privacyVectors = [
    TestVector(
      name: "RingCT Transaction",
      coinName: "particl",
      transactionData: {
        "type": "ringct",
        "inputs": [
          {
            "amount": 0,                    // Amount hidden in RingCT
            "keyImage": "abc123def456789",  // Unique key image
            "ringMembers": 11,              // Ring size
          }
        ],
        "outputs": [
          {
            "stealthAddress": "Sx1FHBi8G5nD2y7EdH9jU4Af3vFZMkN6tKabc123",
            "commitment": "def456abc789123", // Pedersen commitment  
            "rangeProof": "789123abc456def",  // Bulletproof range proof
          }
        ],
        "txFee": 10000,                     // 0.0001 PART
        "ringSignature": "456789def123abc", // Ring signature
      },
    ),
  ];
}

class ParticlTestVectorUtils {
  /// Gets test vectors for Particl operations
  static List<TestVector> getVectorsForOperation(String operation) {
    switch (operation.toLowerCase()) {
      case 'basic':
        return ParticlTestVectors.basicVectors;
      case 'marketplace':
        return ParticlTestVectors.marketplaceVectors;
      case 'staking':
        return ParticlTestVectors.stakingVectors;
      case 'governance':
        return ParticlTestVectors.governanceVectors;
      case 'privacy':
        return ParticlTestVectors.privacyVectors;
      default:
        return ParticlTestVectors.basicVectors;
    }
  }

  /// Gets marketplace test vectors
  static List<TestVector> getMarketplaceVectors() {
    return ParticlTestVectors.marketplaceVectors;
  }

  /// Gets staking test vectors  
  static List<TestVector> getStakingVectors() {
    return ParticlTestVectors.stakingVectors;
  }

  /// Gets governance test vectors
  static List<TestVector> getGovernanceVectors() {
    return ParticlTestVectors.governanceVectors;
  }

  /// Gets privacy test vectors
  static List<TestVector> getPrivacyVectors() {
    return ParticlTestVectors.privacyVectors;
  }

  /// Validates Particl address format
  static bool validateAddress(String address) {
    // Public addresses start with P
    if (address.startsWith('P')) {
      return address.length >= 34 && address.length <= 35;
    }
    
    // Stealth addresses start with S and are longer
    if (address.startsWith('S')) {
      return address.length >= 40;
    }
    
    return false;
  }

  /// Calculates staking reward estimate
  static int calculateStakingReward(int stakedAmount, int days) {
    // Particl has approximately 5% annual staking reward
    const annualRewardRate = 0.05;
    const daysPerYear = 365;
    
    final dailyRate = annualRewardRate / daysPerYear;
    final reward = (stakedAmount * dailyRate * days).round();
    
    return reward;
  }

  /// Calculates cold staking pool fee
  static int calculatePoolFee(int reward, double poolFeePercent) {
    return (reward * poolFeePercent / 100).round();
  }

  /// Validates marketplace listing data
  static bool validateMarketplaceListing(Map<String, dynamic> listing) {
    final requiredFields = ['title', 'description', 'price', 'category'];
    
    for (final field in requiredFields) {
      if (!listing.containsKey(field) || listing[field] == null) {
        return false;
      }
    }
    
    // Price should be positive
    if (listing['price'] is int && listing['price'] <= 0) {
      return false;
    }
    
    return true;
  }

  /// Validates escrow configuration
  static bool validateEscrowConfig(Map<String, dynamic> escrow) {
    final requiredFields = ['buyerDeposit', 'sellerDeposit', 'releaseCondition'];
    
    for (final field in requiredFields) {
      if (!escrow.containsKey(field) || escrow[field] == null) {
        return false;
      }
    }
    
    // Deposits should be positive
    if (escrow['buyerDeposit'] is int && escrow['buyerDeposit'] <= 0) {
      return false;
    }
    
    if (escrow['sellerDeposit'] is int && escrow['sellerDeposit'] <= 0) {
      return false;
    }
    
    return true;
  }

  /// Gets minimum stake amount
  static int getMinimumStakeAmount() {
    return 100000000; // 1 PART minimum
  }

  /// Gets staking maturity time in blocks
  static int getStakingMaturityBlocks() {
    return 8640; // About 24 hours at 2 minutes per block
  }
}