/* 
 * This file is part of Stack Wallet.
 * 
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

class TestVector {
  final String name;
  final String? mnemonic;
  final String coinName;
  final List<String>? expectedAddresses;
  final List<String>? expectedPrivateKeys;
  final Map<String, dynamic>? transactionData;
  final Map<String, dynamic>? stakingData;
  final Map<String, dynamic>? consensusData;
  final Map<String, dynamic>? coinAgeData;
  final Map<String, dynamic>? mintingData;

  const TestVector({
    required this.name,
    this.mnemonic,
    required this.coinName,
    this.expectedAddresses,
    this.expectedPrivateKeys,
    this.transactionData,
    this.stakingData,
    this.consensusData,
    this.coinAgeData,
    this.mintingData,
  });
}

class PeercoinTestVectors {
  static const List<TestVector> basicVectors = [
    TestVector(
      name: "Peercoin Wallet Creation",
      mnemonic: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about",
      coinName: "peercoin",
      expectedAddresses: [
        // Peercoin addresses start with P
        "PV7S5JGdFmT6NkGXWz9fB7LR4R8G3jn2tK",
        "PDV7S5JGdFmT6NkGXWz9fB7LR4R8G3jn2t",
        "PKdFmT6NkGXWz9fB7LR4R8G3jn2tKV7S5J",
      ],
      expectedPrivateKeys: [
        "L53fCHmQhbNp1B4JipfBtfeHZH7cAibzG9oK19XfiFzxHgAkz6JK",
      ],
    ),
    TestVector(
      name: "Peercoin Staking Configuration",
      mnemonic: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about",
      coinName: "peercoin",
      stakingData: {
        "minimumStakeAge": 2592000,      // 30 days in seconds
        "maximumStakeAge": 7776000,      // 90 days in seconds
        "stakingRewardRate": 0.01,       // 1% annual reward
        "stakingDifficulty": 1000000,    // Current PoS difficulty
        "coinWeight": 100000000,         // 1 PPC weight
        "targetSpacing": 600,            // 10 minutes between blocks
      },
    ),
  ];

  static const List<TestVector> stakingVectors = [
    TestVector(
      name: "Coin Age Calculation",
      coinName: "peercoin",
      coinAgeData: {
        "utxo": {
          "amount": 100000000,           // 1 PPC
          "age": 2592000,                // 30 days old (minimum for staking)
          "blockHeight": 100000,
          "currentHeight": 104320,       // 30 days later (4320 blocks/day)
        },
        "calculation": {
          "coinAge": 100000000,          // 1 PPC * 30 days = 30 coin-days
          "stakingWeight": 100000000,    // Effective staking weight
          "eligible": true,              // Eligible for staking
        },
        "maxCoinAge": {
          "amount": 100000000,           // 1 PPC
          "age": 7776000,                // 90 days (maximum)
          "cappedAge": 7776000,          // Capped at 90 days
          "effectiveWeight": 100000000,  // Same as 90-day old coin
        }
      },
    ),
    TestVector(
      name: "Proof of Stake Block Generation",
      coinName: "peercoin",
      mintingData: {
        "kernel": {
          "stakeModifier": "abc123def456789012345678901234567890abcdef12",
          "blockTime": 1640995200,       // Unix timestamp
          "prevBlockTime": 1640994600,   // 10 minutes earlier
          "utxoHash": "def456abc789123456789012345678901234567890abc",
          "utxoN": 0,                    // Output index
        },
        "coinstake": {
          "version": 1,
          "inputAmount": 100000000,      // 1 PPC input
          "outputAmount": 101000000,     // 1.01 PPC output (with reward)
          "timestamp": 1640995200,       // Block timestamp
          "reward": 1000000,             // 0.01 PPC reward (1% annual)
        },
        "blockGeneration": {
          "difficulty": 1000000,         // PoS difficulty
          "targetValue": "0000000000001234567890abcdef123456789012345",
          "hashValue": "0000000000000123456789abcdef0123456789012346",
          "validKernel": true,           // Hash meets difficulty target
        }
      },
    ),
  ];

  static const List<TestVector> consensusVectors = [
    TestVector(
      name: "Hybrid PoW/PoS Consensus",
      coinName: "peercoin",
      consensusData: {
        "powBlock": {
          "type": "proof_of_work",
          "difficulty": 50000000,        // PoW difficulty
          "algorithm": "sha256",         // SHA-256 hashing
          "blockReward": 0,              // No block reward for PoW
          "energyConsumption": "high",   // High energy usage
        },
        "posBlock": {
          "type": "proof_of_stake",
          "difficulty": 1000000,        // PoS difficulty (separate)
          "stakingReward": 1000000,     // 0.01 PPC reward
          "energyConsumption": "minimal", // Minimal energy usage
          "consensusParticipation": 0.1, // 10% of coins participate
        },
        "transition": {
          "powPhase": "initial",         // PoW for initial distribution
          "posPhase": "ongoing",         // PoS for ongoing consensus
          "hybridRatio": 0.9,            // 90% PoS, 10% PoW
        }
      },
    ),
    TestVector(
      name: "Security Features",
      coinName: "peercoin",
      consensusData: {
        "checkpoints": {
          "enabled": true,
          "broadcastCheckpoints": true,
          "checkpointInterval": 10000,   // Every 10,000 blocks
          "lastCheckpoint": 500000,      // Block height
        },
        "stakingAttacks": {
          "nothingAtStake": {
            "mitigation": "checkpoint_system",
            "riskLevel": "low",
          },
          "longRangeAttack": {
            "mitigation": "checkpoint_broadcasting",
            "riskLevel": "minimal",
          },
          "doubleSpending": {
            "mitigation": "coin_age_requirement",
            "confirmations": 6,          // Required confirmations
          }
        }
      },
    ),
  ];

  static const List<TestVector> transactionVectors = [
    TestVector(
      name: "Coinstake Transaction",
      coinName: "peercoin",
      transactionData: {
        "type": "coinstake",
        "version": 1,
        "inputs": [
          {
            "txid": "d5d9b75eb86ac9b2e3dd99c7d4b7fe16acbc1ac4f21a3e8f5e7c9f7e4a8b5c3d",
            "vout": 0,
            "value": 100000000,          // 1 PPC
            "age": 2592000,              // 30 days old
            "scriptSig": "staking_signature",
          }
        ],
        "outputs": [
          {
            "address": "PV7S5JGdFmT6NkGXWz9fB7LR4R8G3jn2tK",
            "value": 101000000,          // 1.01 PPC (with reward)
            "scriptPubKey": "OP_DUP OP_HASH160 ... OP_EQUALVERIFY OP_CHECKSIG",
          }
        ],
        "timestamp": 1640995200,         // Block timestamp
        "blockHash": "0000000000000123456789abcdef0123456789012345678901234567890abc",
      },
    ),
  ];

  static const List<TestVector> efficiencyVectors = [
    TestVector(
      name: "Energy Efficiency Comparison",
      coinName: "peercoin",
      consensusData: {
        "energyComparison": {
          "bitcoin": {
            "algorithm": "sha256_pow",
            "energyPerTx": 700000,       // ~700 kWh per transaction
            "annualConsumption": 150000, // TWh per year
          },
          "peercoin": {
            "algorithm": "hybrid_pos",
            "energyPerTx": 0.1,          // ~0.1 kWh per transaction  
            "annualConsumption": 0.01,   // TWh per year
            "efficiencyGain": 7000000,   // 7M times more efficient
          }
        },
        "sustainability": {
          "carbonFootprint": "minimal",
          "renewableEnergy": true,
          "scalability": "high",
          "longTermViability": true,
        }
      },
    ),
  ];
}

class PeercoinTestVectorUtils {
  /// Gets test vectors for Peercoin operations
  static List<TestVector> getVectorsForOperation(String operation) {
    switch (operation.toLowerCase()) {
      case 'basic':
        return PeercoinTestVectors.basicVectors;
      case 'staking':
        return PeercoinTestVectors.stakingVectors;
      case 'consensus':
        return PeercoinTestVectors.consensusVectors;
      case 'transactions':
        return PeercoinTestVectors.transactionVectors;
      case 'efficiency':
        return PeercoinTestVectors.efficiencyVectors;
      default:
        return PeercoinTestVectors.basicVectors;
    }
  }

  /// Gets staking test vectors
  static List<TestVector> getStakingVectors() {
    return PeercoinTestVectors.stakingVectors;
  }

  /// Gets consensus test vectors
  static List<TestVector> getConsensusVectors() {
    return PeercoinTestVectors.consensusVectors;
  }

  /// Gets efficiency test vectors
  static List<TestVector> getEfficiencyVectors() {
    return PeercoinTestVectors.efficiencyVectors;
  }

  /// Validates Peercoin address format
  static bool validateAddress(String address) {
    // Peercoin addresses start with P
    if (!address.startsWith('P')) return false;
    
    // Should be 34-35 characters long
    if (address.length < 34 || address.length > 35) return false;
    
    // Basic format validation
    final validChars = RegExp(r'^[123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz]+$');
    return validChars.hasMatch(address);
  }

  /// Calculates coin age in coin-days
  static double calculateCoinAge(int amount, int ageInSeconds) {
    const secondsPerDay = 86400;
    final ageInDays = ageInSeconds / secondsPerDay;
    final coinAmount = amount / 1000000; // Convert from satoshis to PPC
    return coinAmount * ageInDays;
  }

  /// Calculates staking probability
  static double calculateStakingProbability(int amount, int ageInSeconds, int difficulty) {
    const minStakeAge = 2592000; // 30 days
    const maxStakeAge = 7776000; // 90 days
    
    // Must meet minimum age requirement
    if (ageInSeconds < minStakeAge) return 0.0;
    
    // Cap age at maximum
    final effectiveAge = ageInSeconds > maxStakeAge ? maxStakeAge : ageInSeconds;
    
    // Simplified probability calculation
    final coinWeight = amount * effectiveAge / minStakeAge;
    final probability = coinWeight.toDouble() / difficulty;
    
    return probability;
  }

  /// Calculates annual staking reward
  static int calculateStakingReward(int stakedAmount, double stakingRate) {
    // Peercoin has approximately 1% annual staking reward
    return (stakedAmount * stakingRate).round();
  }

  /// Validates coin age requirements
  static bool validateCoinAgeRequirements(int ageInSeconds) {
    const minStakeAge = 2592000; // 30 days minimum
    return ageInSeconds >= minStakeAge;
  }

  /// Gets effective staking weight (capped at 90 days)
  static int getEffectiveStakingWeight(int amount, int ageInSeconds) {
    const minStakeAge = 2592000; // 30 days
    const maxStakeAge = 7776000; // 90 days
    
    if (ageInSeconds < minStakeAge) return 0;
    
    final effectiveAge = ageInSeconds > maxStakeAge ? maxStakeAge : ageInSeconds;
    return (amount * effectiveAge / minStakeAge).round();
  }

  /// Calculates PoS difficulty adjustment
  static int calculatePosDifficulty(int currentDifficulty, int actualSpacing, int targetSpacing) {
    const adjustmentFactor = 0.25; // 25% max adjustment per period
    
    final ratio = targetSpacing.toDouble() / actualSpacing;
    final adjustment = (ratio - 1.0) * adjustmentFactor;
    
    return (currentDifficulty * (1.0 + adjustment)).round();
  }

  /// Validates coinstake transaction structure
  static bool validateCoinstakeTransaction(Map<String, dynamic> tx) {
    // Must have timestamp
    if (!tx.containsKey('timestamp') || tx['timestamp'] == null) return false;
    
    // Must have at least one input and output
    if (!tx.containsKey('inputs') || tx['inputs'] == null || (tx['inputs'] as List).isEmpty) return false;
    if (!tx.containsKey('outputs') || tx['outputs'] == null || (tx['outputs'] as List).isEmpty) return false;
    
    // Output value should be greater than input (includes reward)
    final inputs = tx['inputs'] as List;
    final outputs = tx['outputs'] as List;
    
    int totalInput = 0;
    int totalOutput = 0;
    
    for (final input in inputs) {
      if (input['value'] != null) totalInput += input['value'] as int;
    }
    
    for (final output in outputs) {
      if (output['value'] != null) totalOutput += output['value'] as int;
    }
    
    // Output should be greater than input (reward added)
    return totalOutput > totalInput;
  }

  /// Gets minimum and maximum stake age
  static Map<String, int> getStakeAgeRequirements() {
    return {
      'minimum': 2592000, // 30 days
      'maximum': 7776000, // 90 days
    };
  }

  /// Gets current staking parameters
  static Map<String, dynamic> getStakingParameters() {
    return {
      'annualReward': 0.01,        // 1% annual reward
      'targetSpacing': 600,        // 10 minutes between blocks
      'minStakeAge': 2592000,      // 30 days minimum
      'maxStakeAge': 7776000,      // 90 days maximum
      'stakingMaturity': 500,      // Blocks until reward spendable
    };
  }
}