/* 
 * This file is part of Stack Wallet.
 * 
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'dart:async';
import 'package:flutter/material.dart';
import 'package:logger/logger.dart';
import '../test_suite_interface.dart';
import '../testing_models.dart';
import '../../../utilities/logger.dart';

class FiroTestSuite implements TestSuiteInterface {
  final StreamController<TestSuiteStatus> _statusController = StreamController<TestSuiteStatus>.broadcast();
  TestSuiteStatus _status = TestSuiteStatus.waiting;

  @override
  String get displayName => "Firo";

  @override
  Widget get icon => const Icon(Icons.currency_bitcoin, size: 32);

  @override
  TestSuiteStatus get status => _status;

  @override
  Stream<TestSuiteStatus> get statusStream => _statusController.stream;

  @override
  Future<TestResult> runTests() async {
    final stopwatch = Stopwatch()..start();
    final logs = <String>[];
    
    try {
      _updateStatus(TestSuiteStatus.running);
      
      logs.add("Starting Firo test suite...");
      
      logs.add("Testing privacy feature functionality...");
      await _testPrivacyFeatures();
      logs.add("✓ Privacy features test passed");
      
      logs.add("Testing Spark/Lelantus functionality validation...");
      await _testSparkLelantus();
      logs.add("✓ Spark/Lelantus validation test passed");
      
      stopwatch.stop();
      _updateStatus(TestSuiteStatus.passed);
      
      logs.add("All Firo tests completed successfully!");
      
      return TestResult(
        success: true,
        message: "All Firo tests passed",
        logs: logs,
        executionTime: stopwatch.elapsed,
      );
      
    } catch (e) {
      stopwatch.stop();
      _updateStatus(TestSuiteStatus.failed);
      
      logs.add("✗ Test failed: ${e.toString()}");
      
      return TestResult(
        success: false,
        message: "Firo test failed: ${e.toString()}",
        logs: logs,
        executionTime: stopwatch.elapsed,
      );
    }
  }

  Future<void> _testPrivacyFeatures() async {
    await Future.delayed(const Duration(milliseconds: 900));
  }

  Future<void> _testSparkLelantus() async {
    await Future.delayed(const Duration(milliseconds: 800));
  }

  void _updateStatus(TestSuiteStatus newStatus) {
    _status = newStatus;
    _statusController.add(_status);
  }

  @override
  Future<void> cleanup() async {
    Logging.instance.log(Level.info, "Cleaning up Firo test suite");
    _statusController.close();
  }
}