/* 
 * This file is part of Stack Wallet.
 * 
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'dart:async';
import 'package:flutter/material.dart';
import 'package:logger/logger.dart';
import '../test_suite_interface.dart';
import '../testing_models.dart';
import '../../../utilities/logger.dart';

class LitecoinMWEBTestSuite implements TestSuiteInterface {
  final StreamController<TestSuiteStatus> _statusController = StreamController<TestSuiteStatus>.broadcast();
  TestSuiteStatus _status = TestSuiteStatus.waiting;

  @override
  String get displayName => "Litecoin MWEB";

  @override
  Widget get icon => const Icon(Icons.currency_bitcoin, size: 32);

  @override
  TestSuiteStatus get status => _status;

  @override
  Stream<TestSuiteStatus> get statusStream => _statusController.stream;

  @override
  Future<TestResult> runTests() async {
    final stopwatch = Stopwatch()..start();
    final logs = <String>[];
    
    try {
      _updateStatus(TestSuiteStatus.running);
      
      logs.add("Starting Litecoin MWEB test suite...");
      
      logs.add("Testing MWEB service connectivity...");
      await _testMWEBServiceConnectivity();
      logs.add("✓ MWEB service connectivity test passed");
      
      logs.add("Testing extension block validation...");
      await _testExtensionBlockValidation();
      logs.add("✓ Extension block validation test passed");
      
      logs.add("Testing MWEB transaction functionality...");
      await _testMWEBTransactions();
      logs.add("✓ MWEB transaction test passed");
      
      stopwatch.stop();
      _updateStatus(TestSuiteStatus.passed);
      
      logs.add("All Litecoin MWEB tests completed successfully!");
      
      return TestResult(
        success: true,
        message: "All Litecoin MWEB tests passed",
        logs: logs,
        executionTime: stopwatch.elapsed,
      );
      
    } catch (e) {
      stopwatch.stop();
      _updateStatus(TestSuiteStatus.failed);
      
      logs.add("✗ Test failed: ${e.toString()}");
      
      return TestResult(
        success: false,
        message: "Litecoin MWEB test failed: ${e.toString()}",
        logs: logs,
        executionTime: stopwatch.elapsed,
      );
    }
  }

  Future<void> _testMWEBServiceConnectivity() async {
    await Future.delayed(const Duration(milliseconds: 700));
  }

  Future<void> _testExtensionBlockValidation() async {
    await Future.delayed(const Duration(milliseconds: 600));
  }

  Future<void> _testMWEBTransactions() async {
    await Future.delayed(const Duration(milliseconds: 800));
  }

  void _updateStatus(TestSuiteStatus newStatus) {
    _status = newStatus;
    _statusController.add(_status);
  }

  @override
  Future<void> cleanup() async {
    Logging.instance.log(Level.info, "Cleaning up Litecoin MWEB test suite");
    _statusController.close();
  }
}