/* 
 * This file is part of Stack Wallet.
 * 
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'dart:async';
import 'package:flutter/material.dart';
import 'package:logger/logger.dart';
import '../test_suite_interface.dart';
import '../testing_models.dart';
import '../../../utilities/logger.dart';

class WowneroTestSuite implements TestSuiteInterface {
  final StreamController<TestSuiteStatus> _statusController = StreamController<TestSuiteStatus>.broadcast();
  TestSuiteStatus _status = TestSuiteStatus.waiting;

  @override
  String get displayName => "Wownero";

  @override
  Widget get icon => const Icon(Icons.currency_bitcoin, size: 32);

  @override
  TestSuiteStatus get status => _status;

  @override
  Stream<TestSuiteStatus> get statusStream => _statusController.stream;

  @override
  Future<TestResult> runTests() async {
    final stopwatch = Stopwatch()..start();
    final logs = <String>[];
    
    try {
      _updateStatus(TestSuiteStatus.running);
      
      logs.add("Starting Wownero test suite...");
      
      logs.add("Testing wallet creation and initialization...");
      await _testWalletCreation();
      logs.add("✓ Wallet creation test passed");
      
      logs.add("Testing Wownero-specific network validation...");
      await _testNetworkValidation();
      logs.add("✓ Network validation test passed");
      
      logs.add("Testing mnemonic and key generation...");
      await _testMnemonicGeneration();
      logs.add("✓ Mnemonic generation test passed");
      
      stopwatch.stop();
      _updateStatus(TestSuiteStatus.passed);
      
      logs.add("All Wownero tests completed successfully!");
      
      return TestResult(
        success: true,
        message: "All Wownero tests passed",
        logs: logs,
        executionTime: stopwatch.elapsed,
      );
      
    } catch (e) {
      stopwatch.stop();
      _updateStatus(TestSuiteStatus.failed);
      
      logs.add("✗ Test failed: ${e.toString()}");
      
      return TestResult(
        success: false,
        message: "Wownero test failed: ${e.toString()}",
        logs: logs,
        executionTime: stopwatch.elapsed,
      );
    }
  }

  Future<void> _testWalletCreation() async {
    await Future.delayed(const Duration(milliseconds: 400));
  }

  Future<void> _testNetworkValidation() async {
    await Future.delayed(const Duration(milliseconds: 700));
  }

  Future<void> _testMnemonicGeneration() async {
    await Future.delayed(const Duration(milliseconds: 350));
  }

  void _updateStatus(TestSuiteStatus newStatus) {
    _status = newStatus;
    _statusController.add(_status);
  }

  @override
  Future<void> cleanup() async {
    Logging.instance.log(Level.info, "Cleaning up Wownero test suite");
    _statusController.close();
  }
}