/* 
 * This file is part of Stack Wallet.
 * 
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'dart:io';
import 'package:flutter/material.dart';
import 'package:file_picker/file_picker.dart';
import 'package:path/path.dart' as path;

import '../../../themes/stack_colors.dart';
import '../../../utilities/text_styles.dart';
import '../../../utilities/util.dart';
import '../../../widgets/rounded_white_container.dart';

class BackupFileUploader extends StatefulWidget {
  const BackupFileUploader({
    super.key,
    this.selectedFilePath,
    required this.onFileSelected,
    this.onClearFile,
    this.enabled = true,
  });

  final String? selectedFilePath;
  final ValueChanged<String> onFileSelected;
  final VoidCallback? onClearFile;
  final bool enabled;

  @override
  State<BackupFileUploader> createState() => _BackupFileUploaderState();
}

class _BackupFileUploaderState extends State<BackupFileUploader> {
  bool _isValidating = false;
  String? _validationError;

  Future<void> _selectFile() async {
    try {
      final result = await FilePicker.platform.pickFiles(
        type: FileType.custom,
        allowedExtensions: ['swb'],
        dialogTitle: 'Select Stack Wallet Backup File',
      );

      if (result != null && result.files.isNotEmpty) {
        final filePath = result.files.first.path;
        if (filePath != null) {
          await _validateFile(filePath);
          if (_validationError == null) {
            widget.onFileSelected(filePath);
          }
        }
      }
    } catch (e) {
      setState(() {
        _validationError = "Error selecting file: ${e.toString()}";
      });
    }
  }

  Future<void> _validateFile(String filePath) async {
    setState(() {
      _isValidating = true;
      _validationError = null;
    });

    try {
      final file = File(filePath);
      
      // Check if file exists
      if (!await file.exists()) {
        throw Exception("File does not exist");
      }
      
      // Check file extension
      if (!filePath.toLowerCase().endsWith('.swb')) {
        throw Exception("File must have .swb extension");
      }
      
      // Check file size
      final stat = await file.stat();
      if (stat.size == 0) {
        throw Exception("File is empty");
      }
      
      if (stat.size > 100 * 1024 * 1024) { // 100MB
        throw Exception("File is too large (max 100MB)");
      }
      
      // Basic readability check
      try {
        final bytes = await file.readAsBytes();
        if (bytes.isEmpty) {
          throw Exception("Cannot read file contents");
        }
      } catch (e) {
        throw Exception("Cannot read file: $e");
      }
      
    } catch (e) {
      setState(() {
        _validationError = e.toString();
      });
    } finally {
      setState(() {
        _isValidating = false;
      });
    }
  }

  String _formatFileSize(int bytes) {
    if (bytes < 1024) return "${bytes}B";
    if (bytes < 1024 * 1024) return "${(bytes / 1024).toStringAsFixed(1)}KB";
    return "${(bytes / (1024 * 1024)).toStringAsFixed(1)}MB";
  }

  Future<Map<String, dynamic>?> _getFileInfo(String filePath) async {
    try {
      final file = File(filePath);
      final stat = await file.stat();
      return {
        'name': path.basename(filePath),
        'size': _formatFileSize(stat.size),
        'modified': stat.modified,
      };
    } catch (e) {
      return null;
    }
  }

  @override
  Widget build(BuildContext context) {
    final colors = Theme.of(context).extension<StackColors>()!;

    return RoundedWhiteContainer(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Text(
                "Backup File",
                style: STextStyles.titleBold12(context),
              ),
              if (widget.selectedFilePath != null) ...[
                const Spacer(),
                if (widget.enabled)
                  GestureDetector(
                    onTap: widget.onClearFile,
                    child: Container(
                      padding: const EdgeInsets.all(4),
                      decoration: BoxDecoration(
                        color: colors.accentColorRed.withOpacity(0.1),
                        borderRadius: BorderRadius.circular(4),
                      ),
                      child: Icon(
                        Icons.close,
                        size: 16,
                        color: colors.accentColorRed,
                      ),
                    ),
                  ),
              ],
            ],
          ),
          
          const SizedBox(height: 12),
          
          if (widget.selectedFilePath == null) ...[
            // File selection area
            GestureDetector(
              onTap: widget.enabled ? _selectFile : null,
              child: Container(
                width: double.infinity,
                padding: const EdgeInsets.all(16),
                decoration: BoxDecoration(
                  border: Border.all(
                    color: _validationError != null 
                        ? colors.accentColorRed 
                        : colors.textFieldDefaultBG,
                    style: BorderStyle.dashed,
                    width: 2,
                  ),
                  borderRadius: BorderRadius.circular(8),
                  color: widget.enabled 
                      ? colors.textFieldDefaultBG.withOpacity(0.3)
                      : colors.textFieldDefaultBG,
                ),
                child: Column(
                  children: [
                    Icon(
                      Icons.cloud_upload_outlined,
                      size: 48,
                      color: widget.enabled 
                          ? colors.accentColorBlue 
                          : colors.textSubtitle1,
                    ),
                    const SizedBox(height: 8),
                    Text(
                      widget.enabled 
                          ? "Select Stack Wallet Backup File (.swb)"
                          : "File selection disabled",
                      style: STextStyles.label(context).copyWith(
                        color: widget.enabled 
                            ? colors.textDark 
                            : colors.textSubtitle1,
                        fontWeight: FontWeight.w500,
                      ),
                    ),
                    if (widget.enabled) ...[
                      const SizedBox(height: 4),
                      Text(
                        "Tap to browse files",
                        style: STextStyles.label(context).copyWith(
                          color: colors.textSubtitle1,
                        ),
                      ),
                    ],
                  ],
                ),
              ),
            ),
          ] else ...[
            // Selected file display
            Container(
              width: double.infinity,
              padding: const EdgeInsets.all(12),
              decoration: BoxDecoration(
                color: colors.accentColorGreen.withOpacity(0.1),
                border: Border.all(
                  color: colors.accentColorGreen,
                  width: 1,
                ),
                borderRadius: BorderRadius.circular(8),
              ),
              child: FutureBuilder<Map<String, dynamic>?>(
                future: _getFileInfo(widget.selectedFilePath!),
                builder: (context, snapshot) {
                  final fileInfo = snapshot.data;
                  return Row(
                    children: [
                      Icon(
                        Icons.check_circle,
                        color: colors.accentColorGreen,
                        size: 20,
                      ),
                      const SizedBox(width: 8),
                      Expanded(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(
                              fileInfo?['name'] ?? path.basename(widget.selectedFilePath!),
                              style: STextStyles.titleBold12(context).copyWith(
                                color: colors.accentColorGreen,
                              ),
                            ),
                            if (fileInfo != null) ...[
                              const SizedBox(height: 2),
                              Text(
                                "Size: ${fileInfo['size']} • Modified: ${Util.dateTimeToString(fileInfo['modified'])}",
                                style: STextStyles.label(context).copyWith(
                                  color: colors.textSubtitle1,
                                ),
                              ),
                            ],
                          ],
                        ),
                      ),
                    ],
                  );
                },
              ),
            ),
          ],
          
          // Validation feedback
          if (_isValidating) ...[
            const SizedBox(height: 8),
            Row(
              children: [
                SizedBox(
                  width: 16,
                  height: 16,
                  child: CircularProgressIndicator(
                    strokeWidth: 2,
                    valueColor: AlwaysStoppedAnimation<Color>(colors.accentColorBlue),
                  ),
                ),
                const SizedBox(width: 8),
                Text(
                  "Validating file...",
                  style: STextStyles.label(context).copyWith(
                    color: colors.textSubtitle1,
                  ),
                ),
              ],
            ),
          ],
          
          if (_validationError != null) ...[
            const SizedBox(height: 8),
            Container(
              padding: const EdgeInsets.all(8),
              decoration: BoxDecoration(
                color: colors.accentColorRed.withOpacity(0.1),
                borderRadius: BorderRadius.circular(4),
              ),
              child: Row(
                children: [
                  Icon(
                    Icons.error_outline,
                    color: colors.accentColorRed,
                    size: 16,
                  ),
                  const SizedBox(width: 8),
                  Expanded(
                    child: Text(
                      _validationError!,
                      style: STextStyles.label(context).copyWith(
                        color: colors.accentColorRed,
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ],
        ],
      ),
    );
  }
}