/* 
 * This file is part of Stack Wallet.
 * 
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

import '../../../themes/stack_colors.dart';
import '../../../utilities/text_styles.dart';
import '../../../widgets/stack_dialog.dart';
import '../../../widgets/stack_text_field.dart';

class PassphraseInputDialog extends StatefulWidget {
  const PassphraseInputDialog({
    super.key,
    required this.backupFilePath,
  });

  final String backupFilePath;

  @override
  State<PassphraseInputDialog> createState() => _PassphraseInputDialogState();
}

class _PassphraseInputDialogState extends State<PassphraseInputDialog> {
  final TextEditingController _passphraseController = TextEditingController();
  final FocusNode _passphraseFocusNode = FocusNode();
  
  bool _hidePassphrase = true;
  bool _isValidating = false;
  String? _validationError;
  
  @override
  void initState() {
    super.initState();
    // Auto-focus passphrase field when dialog opens
    WidgetsBinding.instance.addPostFrameCallback((_) {
      _passphraseFocusNode.requestFocus();
    });
  }

  @override
  void dispose() {
    _passphraseController.dispose();
    _passphraseFocusNode.dispose();
    super.dispose();
  }

  Future<void> _validateAndConfirm() async {
    if (_passphraseController.text.trim().isEmpty) {
      setState(() {
        _validationError = "Passphrase cannot be empty";
      });
      return;
    }

    setState(() {
      _isValidating = true;
      _validationError = null;
    });

    try {
      // In a real implementation, you might want to do a quick validation
      // by attempting to decrypt just the header of the backup file
      // For now, we'll just simulate a brief validation delay
      await Future.delayed(const Duration(milliseconds: 500));
      
      // Return the passphrase to the caller
      if (mounted) {
        Navigator.of(context).pop(_passphraseController.text);
      }
    } catch (e) {
      setState(() {
        _validationError = "Invalid passphrase or corrupted backup file";
        _isValidating = false;
      });
    }
  }

  void _cancel() {
    Navigator.of(context).pop(null);
  }

  @override
  Widget build(BuildContext context) {
    final colors = Theme.of(context).extension<StackColors>()!;

    return StackDialog(
      title: "Enter Backup Passphrase",
      message: "Please enter the passphrase for your Stack Wallet backup file.",
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          const SizedBox(height: 16),
          
          // File info
          Container(
            width: double.infinity,
            padding: const EdgeInsets.all(12),
            decoration: BoxDecoration(
              color: colors.textFieldDefaultBG,
              borderRadius: BorderRadius.circular(8),
            ),
            child: Row(
              children: [
                Icon(
                  Icons.backup,
                  size: 20,
                  color: colors.textSubtitle1,
                ),
                const SizedBox(width: 8),
                Expanded(
                  child: Text(
                    widget.backupFilePath.split('/').last,
                    style: STextStyles.label(context).copyWith(
                      color: colors.textDark,
                      fontWeight: FontWeight.w500,
                    ),
                    overflow: TextOverflow.ellipsis,
                  ),
                ),
              ],
            ),
          ),
          
          const SizedBox(height: 16),
          
          // Passphrase input field
          StackTextField(
            controller: _passphraseController,
            focusNode: _passphraseFocusNode,
            hintText: "Enter backup passphrase",
            obscureText: _hidePassphrase,
            textInputAction: TextInputAction.done,
            onSubmitted: (_) => _validateAndConfirm(),
            suffixIcon: Padding(
              padding: const EdgeInsets.only(right: 8),
              child: GestureDetector(
                onTap: () {
                  setState(() {
                    _hidePassphrase = !_hidePassphrase;
                  });
                },
                child: Container(
                  width: 24,
                  height: 24,
                  decoration: BoxDecoration(
                    color: colors.textFieldDefaultBG,
                    borderRadius: BorderRadius.circular(4),
                  ),
                  child: Icon(
                    _hidePassphrase ? Icons.visibility : Icons.visibility_off,
                    size: 16,
                    color: colors.textSubtitle1,
                  ),
                ),
              ),
            ),
            inputFormatters: [
              // Prevent newlines and trim whitespace
              FilteringTextInputFormatter.deny(RegExp(r'[\n\r]')),
            ],
          ),
          
          // Validation feedback
          if (_validationError != null) ...[
            const SizedBox(height: 8),
            Container(
              width: double.infinity,
              padding: const EdgeInsets.all(8),
              decoration: BoxDecoration(
                color: colors.accentColorRed.withOpacity(0.1),
                borderRadius: BorderRadius.circular(4),
              ),
              child: Row(
                children: [
                  Icon(
                    Icons.error_outline,
                    color: colors.accentColorRed,
                    size: 16,
                  ),
                  const SizedBox(width: 8),
                  Expanded(
                    child: Text(
                      _validationError!,
                      style: STextStyles.label(context).copyWith(
                        color: colors.accentColorRed,
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ],
          
          if (_isValidating) ...[
            const SizedBox(height: 16),
            Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                SizedBox(
                  width: 16,
                  height: 16,
                  child: CircularProgressIndicator(
                    strokeWidth: 2,
                    valueColor: AlwaysStoppedAnimation<Color>(colors.accentColorBlue),
                  ),
                ),
                const SizedBox(width: 12),
                Text(
                  "Validating passphrase...",
                  style: STextStyles.label(context).copyWith(
                    color: colors.textSubtitle1,
                  ),
                ),
              ],
            ),
          ],
          
          const SizedBox(height: 24),
          
          // Action buttons
          Row(
            children: [
              Expanded(
                child: TextButton(
                  onPressed: _isValidating ? null : _cancel,
                  style: colors.getSecondaryEnabledButtonStyle(context),
                  child: Text(
                    "Cancel",
                    style: STextStyles.button(context).copyWith(
                      color: colors.buttonTextSecondary,
                    ),
                  ),
                ),
              ),
              const SizedBox(width: 16),
              Expanded(
                child: TextButton(
                  onPressed: _isValidating ? null : _validateAndConfirm,
                  style: _isValidating 
                      ? colors.getPrimaryDisabledButtonStyle(context)
                      : colors.getPrimaryEnabledButtonStyle(context),
                  child: Text(
                    "Confirm",
                    style: STextStyles.button(context).copyWith(
                      color: _isValidating
                          ? colors.buttonTextPrimaryDisabled
                          : colors.buttonTextPrimary,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  /// Static method to show the dialog and return the passphrase
  static Future<String?> show(BuildContext context, String backupFilePath) async {
    return await showDialog<String>(
      context: context,
      barrierDismissible: false,
      builder: (context) => PassphraseInputDialog(backupFilePath: backupFilePath),
    );
  }
}