/* 
 * This file is part of Stack Wallet.
 * 
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'package:flutter/material.dart';

import '../../../themes/stack_colors.dart';
import '../../../utilities/text_styles.dart';
import '../../../widgets/progress_bar.dart';
import '../../../widgets/rounded_white_container.dart';

class TestingProgressIndicator extends StatelessWidget {
  const TestingProgressIndicator({
    super.key,
    required this.completed,
    required this.total,
    required this.isRunning,
  });

  final int completed;
  final int total;
  final bool isRunning;

  @override
  Widget build(BuildContext context) {
    final colors = Theme.of(context).extension<StackColors>()!;
    final progress = total > 0 ? completed / total : 0.0;

    return RoundedWhiteContainer(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text(
                isRunning ? "Running Tests..." : "Test Progress",
                style: STextStyles.titleBold12(context),
              ),
              Text(
                "$completed / $total",
                style: STextStyles.label(context).copyWith(
                  color: colors.textSubtitle1,
                ),
              ),
            ],
          ),
          const SizedBox(height: 12),
          ProgressBar(
            key: Key("${completed}_$total"),
            width: double.infinity,
            height: 8,
            fillColor: isRunning 
                ? colors.accentColorBlue 
                : completed == total && total > 0
                    ? colors.accentColorGreen
                    : colors.accentColorBlue,
            backgroundColor: colors.textFieldDefaultBG,
            percent: progress,
          ),
          if (isRunning)
            Padding(
              padding: const EdgeInsets.only(top: 8),
              child: Text(
                "Tests are running in the background...",
                style: STextStyles.label(context).copyWith(
                  color: colors.textSubtitle1,
                  fontStyle: FontStyle.italic,
                ),
              ),
            ),
          if (!isRunning && completed == total && total > 0)
            Padding(
              padding: const EdgeInsets.only(top: 8),
              child: Row(
                children: [
                  Icon(
                    Icons.check_circle,
                    size: 16,
                    color: colors.accentColorGreen,
                  ),
                  const SizedBox(width: 6),
                  Text(
                    "All tests completed!",
                    style: STextStyles.label(context).copyWith(
                      color: colors.accentColorGreen,
                    ),
                  ),
                ],
              ),
            ),
        ],
      ),
    );
  }
}