/* 
 * This file is part of Stack Wallet.
 * 
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'package:flutter/material.dart';

import '../../../services/testing/testing_models.dart';
import '../../../themes/stack_colors.dart';
import '../../../utilities/text_styles.dart';
import '../../../widgets/rounded_white_container.dart';

class TestModeSelector extends StatelessWidget {
  const TestModeSelector({
    super.key,
    required this.selectedMode,
    required this.onModeChanged,
    this.enabled = true,
  });

  final TestingMode selectedMode;
  final ValueChanged<TestingMode> onModeChanged;
  final bool enabled;

  @override
  Widget build(BuildContext context) {
    final colors = Theme.of(context).extension<StackColors>()!;

    return RoundedWhiteContainer(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            "Testing Mode",
            style: STextStyles.titleBold12(context),
          ),
          const SizedBox(height: 12),
          
          // Programmed Vectors Option
          _buildModeOption(
            context,
            colors,
            mode: TestingMode.programmedVectors,
            title: "Programmed Test Vectors",
            description: "Run pre-defined test scenarios with mock data. Fast execution for basic functionality verification.",
            icon: Icons.code,
          ),
          
          const SizedBox(height: 8),
          
          // Backup File Option
          _buildModeOption(
            context,
            colors,
            mode: TestingMode.backupFile,
            title: "Stack Wallet Backup File",
            description: "Restore wallets from .swb backup files and perform self-spend transactions. Tests real wallet functionality.",
            icon: Icons.backup,
          ),
        ],
      ),
    );
  }

  Widget _buildModeOption(
    BuildContext context,
    StackColors colors, {
    required TestingMode mode,
    required String title,
    required String description,
    required IconData icon,
  }) {
    final isSelected = selectedMode == mode;
    
    return GestureDetector(
      onTap: enabled ? () => onModeChanged(mode) : null,
      child: Container(
        padding: const EdgeInsets.all(12),
        decoration: BoxDecoration(
          border: Border.all(
            color: isSelected 
                ? colors.accentColorBlue 
                : colors.textFieldDefaultBG,
            width: 2,
          ),
          borderRadius: BorderRadius.circular(8),
          color: enabled 
              ? (isSelected ? colors.accentColorBlue.withOpacity(0.1) : Colors.transparent)
              : colors.textFieldDefaultBG,
        ),
        child: Row(
          children: [
            // Radio button
            Container(
              width: 20,
              height: 20,
              decoration: BoxDecoration(
                shape: BoxShape.circle,
                border: Border.all(
                  color: isSelected 
                      ? colors.accentColorBlue 
                      : colors.textSubtitle1,
                  width: 2,
                ),
                color: isSelected 
                    ? colors.accentColorBlue 
                    : Colors.transparent,
              ),
              child: isSelected
                  ? Center(
                      child: Container(
                        width: 8,
                        height: 8,
                        decoration: BoxDecoration(
                          shape: BoxShape.circle,
                          color: colors.background,
                        ),
                      ),
                    )
                  : null,
            ),
            
            const SizedBox(width: 12),
            
            // Icon
            Icon(
              icon,
              size: 24,
              color: isSelected 
                  ? colors.accentColorBlue 
                  : colors.textSubtitle1,
            ),
            
            const SizedBox(width: 12),
            
            // Content
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    title,
                    style: STextStyles.titleBold12(context).copyWith(
                      color: enabled 
                          ? (isSelected ? colors.accentColorBlue : colors.textDark)
                          : colors.textSubtitle1,
                    ),
                  ),
                  const SizedBox(height: 4),
                  Text(
                    description,
                    style: STextStyles.label(context).copyWith(
                      color: enabled 
                          ? colors.textSubtitle1
                          : colors.textSubtitle1.withOpacity(0.6),
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}