/* 
 * This file is part of Stack Wallet.
 * 
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'dart:convert';
import 'dart:io';
import 'package:logger/logger.dart';
import 'package:tuple/tuple.dart';

import '../../../utilities/logger.dart';
import '../../settings_views/global_settings_view/stack_backup_views/helpers/restore_create_backup.dart';

class BackupFileHandler {
  /// Validates backup file format and readability
  Future<bool> validateBackupFile(String filePath) async {
    try {
      final file = File(filePath);
      
      // Check if file exists and is readable
      if (!await file.exists()) {
        Logging.instance.log(Level.error, "Backup file does not exist: $filePath");
        return false;
      }
      
      // Check file extension
      if (!filePath.toLowerCase().endsWith('.swb')) {
        Logging.instance.log(Level.warning, "File does not have .swb extension: $filePath");
      }
      
      // Check if file is not empty
      final stat = await file.stat();
      if (stat.size == 0) {
        Logging.instance.log(Level.error, "Backup file is empty: $filePath");
        return false;
      }
      
      // Check if file is reasonably sized (between 1KB and 100MB)
      if (stat.size < 1024) {
        Logging.instance.log(Level.warning, "Backup file seems too small: ${stat.size} bytes");
      } else if (stat.size > 100 * 1024 * 1024) {
        Logging.instance.log(Level.warning, "Backup file seems very large: ${stat.size} bytes");
      }
      
      Logging.instance.log(Level.info, "Backup file validation passed: $filePath (${stat.size} bytes)");
      return true;
    } catch (e) {
      Logging.instance.log(Level.error, "Error validating backup file: $e");
      return false;
    }
  }

  /// Decrypts backup file with provided passphrase
  Future<String> decryptBackupFile(String filePath, String passphrase) async {
    try {
      Logging.instance.log(Level.info, "Attempting to decrypt backup file: $filePath");
      
      // Use the existing SWB class for decryption
      final jsonString = await SWB.decryptStackWalletWithPassphrase(
        Tuple2(filePath, passphrase),
      );
      
      if (jsonString.isEmpty) {
        throw Exception("Decrypted content is empty");
      }
      
      Logging.instance.log(Level.info, "Successfully decrypted backup file (${jsonString.length} characters)");
      return jsonString;
    } catch (e) {
      Logging.instance.log(Level.error, "Failed to decrypt backup file: $e");
      rethrow;
    }
  }

  /// Parses decrypted JSON and extracts wallet data
  Future<BackupData> parseBackupData(String decryptedJson) async {
    try {
      Logging.instance.log(Level.info, "Parsing backup data JSON");
      
      final Map<String, dynamic> json = jsonDecode(decryptedJson);
      
      // Extract main sections
      final preferences = json['prefs'] as Map<String, dynamic>? ?? {};
      final nodes = json['nodes'] as List<dynamic>? ?? [];
      final addressBook = json['addressBookEntries'] as List<dynamic>? ?? [];
      final tradeHistory = json['tradeHistory'] as Map<String, dynamic>? ?? {};
      
      // Parse wallet data
      final walletsJson = json['wallets'] as List<dynamic>? ?? [];
      final wallets = <WalletBackupData>[];
      
      for (final walletJson in walletsJson) {
        if (walletJson is Map<String, dynamic>) {
          try {
            final walletData = WalletBackupData.fromJson(walletJson);
            wallets.add(walletData);
          } catch (e) {
            Logging.instance.log(Level.warning, "Failed to parse wallet data: $e");
          }
        }
      }
      
      final backupData = BackupData(
        preferences: preferences,
        nodes: nodes,
        wallets: wallets,
        addressBook: addressBook,
        tradeHistory: tradeHistory,
      );
      
      Logging.instance.log(Level.info, "Successfully parsed backup data: ${wallets.length} wallets found");
      return backupData;
    } catch (e) {
      Logging.instance.log(Level.error, "Failed to parse backup data: $e");
      rethrow;
    }
  }

  /// Validates wallet data for testing compatibility
  Future<List<WalletBackupData>> getTestableWallets(BackupData backup) async {
    final testableWallets = <WalletBackupData>[];
    
    for (final wallet in backup.wallets) {
      if (await _isWalletTestable(wallet)) {
        testableWallets.add(wallet);
      } else {
        Logging.instance.log(Level.info, "Wallet ${wallet.name} (${wallet.coinName}) is not testable");
      }
    }
    
    Logging.instance.log(Level.info, "Found ${testableWallets.length} testable wallets out of ${backup.wallets.length}");
    return testableWallets;
  }

  /// Checks if a wallet can be used for testing
  Future<bool> _isWalletTestable(WalletBackupData wallet) async {
    // Must have either mnemonic or private key
    if (wallet.mnemonic == null && wallet.privateKey == null) {
      Logging.instance.log(Level.debug, "Wallet ${wallet.name} has no mnemonic or private key");
      return false;
    }
    
    // Must have a supported coin type
    final supportedCoins = [
      'bitcoin', 'litecoin', 'dogecoin', 'firo', 
      'monero', 'wownero', 'epicCash', 
      'ethereum', 'bitcoincash'
    ];
    
    if (!supportedCoins.contains(wallet.coinName.toLowerCase())) {
      Logging.instance.log(Level.debug, "Wallet ${wallet.name} has unsupported coin: ${wallet.coinName}");
      return false;
    }
    
    // View-only wallets cannot perform transactions
    if (wallet.isViewOnly) {
      Logging.instance.log(Level.debug, "Wallet ${wallet.name} is view-only");
      return false;
    }
    
    return true;
  }
}

class BackupData {
  final Map<String, dynamic> preferences;
  final List<dynamic> nodes;
  final List<WalletBackupData> wallets;
  final List<dynamic> addressBook;
  final Map<String, dynamic> tradeHistory;

  const BackupData({
    required this.preferences,
    required this.nodes,
    required this.wallets,
    required this.addressBook,
    required this.tradeHistory,
  });
}

class WalletBackupData {
  final String id;
  final String name;
  final String coinName;
  final String? mnemonic;
  final String? mnemonicPassphrase;
  final String? privateKey;
  final int? restoreHeight;
  final bool isFavorite;
  final bool isViewOnly;
  final Map<String, dynamic> otherData;

  const WalletBackupData({
    required this.id,
    required this.name,
    required this.coinName,
    this.mnemonic,
    this.mnemonicPassphrase,
    this.privateKey,
    this.restoreHeight,
    required this.isFavorite,
    required this.isViewOnly,
    required this.otherData,
  });

  factory WalletBackupData.fromJson(Map<String, dynamic> json) {
    // Handle mnemonic that could be string or array
    String? mnemonic;
    final mnemonicField = json['mnemonic'];
    if (mnemonicField is String) {
      mnemonic = mnemonicField;
    } else if (mnemonicField is List) {
      mnemonic = (mnemonicField as List<dynamic>).join(' ');
    }

    // Check if it's a view-only wallet
    final viewOnlyKey = json['viewOnlyWalletDataKey'];
    final isViewOnly = viewOnlyKey != null && viewOnlyKey.toString().isNotEmpty;

    return WalletBackupData(
      id: json['id'] as String? ?? '',
      name: json['name'] as String? ?? 'Unknown Wallet',
      coinName: json['coinName'] as String? ?? 'Unknown',
      mnemonic: mnemonic,
      mnemonicPassphrase: json['mnemonicPassphrase'] as String?,
      privateKey: json['privateKey'] as String?,
      restoreHeight: json['restoreHeight'] as int? ?? json['storedChainHeight'] as int?,
      isFavorite: json['isFavorite'] as bool? ?? false,
      isViewOnly: isViewOnly,
      otherData: Map<String, dynamic>.from(json),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'name': name,
      'coinName': coinName,
      'mnemonic': mnemonic,
      'mnemonicPassphrase': mnemonicPassphrase,
      'privateKey': privateKey,
      'restoreHeight': restoreHeight,
      'isFavorite': isFavorite,
      'isViewOnly': isViewOnly,
      ...otherData,
    };
  }
}