/* 
 * This file is part of Stack Wallet.
 * 
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'package:logger/logger.dart';

import '../../../utilities/logger.dart';
import '../../../utilities/amount/amount.dart';
import '../../../wallets/models/tx_data.dart';
import '../../../wallets/wallet/wallet.dart';
import '../testing_models.dart';

class TransactionTestExecutor {
  /// Performs self-spend transaction test
  Future<TransactionTestResult> executeSelfSpendTest(
    Wallet wallet,
    String testAmountString,
    int? feeRate,
  ) async {
    final stopwatch = Stopwatch()..start();
    
    try {
      Logging.instance.log(Level.info, "Starting self-spend test for wallet: ${wallet.info.name}");
      
      // Parse test amount
      final Amount testAmount;
      try {
        testAmount = Amount.fromSerializeableString(testAmountString);
      } catch (e) {
        return TransactionTestResult(
          success: false,
          errorMessage: "Invalid test amount: $testAmountString",
          executionTime: stopwatch.elapsed,
          wasBroadcast: false,
        );
      }

      // Check wallet balance
      final balance = await wallet.balance;
      if (balance.spendable < testAmount) {
        return TransactionTestResult(
          success: false,
          errorMessage: "Insufficient balance. Available: ${balance.spendable}, Required: $testAmount",
          executionTime: stopwatch.elapsed,
          wasBroadcast: false,
        );
      }

      // Create self-spend transaction
      final txData = await createSelfSpendTransaction(wallet, testAmount, feeRate);
      if (txData.txid == null) {
        return TransactionTestResult(
          success: false,
          errorMessage: "Failed to create transaction",
          executionTime: stopwatch.elapsed,
          wasBroadcast: false,
        );
      }

      // Validate transaction
      final isValid = await validateTransaction(txData);
      if (!isValid) {
        return TransactionTestResult(
          success: false,
          errorMessage: "Transaction validation failed",
          executionTime: stopwatch.elapsed,
          wasBroadcast: false,
        );
      }

      // For testing, we typically don't broadcast to avoid spending real funds
      // But we can optionally broadcast to testnet if configured
      bool wasBroadcast = false;
      String? finalTxId = txData.txid;
      
      // Uncomment the following for actual broadcasting (use with caution!)
      // try {
      //   final broadcastResult = await broadcastTransaction(wallet, txData);
      //   if (broadcastResult != null) {
      //     wasBroadcast = true;
      //     finalTxId = broadcastResult;
      //   }
      // } catch (e) {
      //   Logging.instance.log(Level.warning, "Broadcasting failed (this is expected for testing): $e");
      // }

      stopwatch.stop();
      
      Logging.instance.log(Level.info, "Self-spend test completed successfully: ${wallet.info.name}");
      return TransactionTestResult(
        success: true,
        transactionId: finalTxId,
        actualFee: txData.fee?.toSerializeableString(),
        executionTime: stopwatch.elapsed,
        wasBroadcast: wasBroadcast,
      );

    } catch (e) {
      stopwatch.stop();
      Logging.instance.log(Level.error, "Self-spend test failed for ${wallet.info.name}: $e");
      
      return TransactionTestResult(
        success: false,
        errorMessage: e.toString(),
        executionTime: stopwatch.elapsed,
        wasBroadcast: false,
      );
    }
  }

  /// Creates transaction to own address
  Future<TxData> createSelfSpendTransaction(
    Wallet wallet,
    Amount amount,
    int? feeRate,
  ) async {
    try {
      Logging.instance.log(Level.info, "Creating self-spend transaction for ${amount.toSerializeableString()}");
      
      // Get a receive address (sending to ourselves)
      final receiveAddress = await wallet.getCurrentReceivingAddress();
      if (receiveAddress == null) {
        throw Exception("Could not get receive address for wallet");
      }

      // Create recipients list (sending to our own address)
      final recipients = [
        TxRecipient(
          address: receiveAddress.value,
          amount: amount,
          isChange: false,
        ),
      ];

      // Build initial transaction data
      TxData txData = TxData(recipients: recipients);
      
      // Set fee rate if provided
      if (feeRate != null) {
        txData = txData.copyWith(
          feeRatePerKB: feeRate * 1000, // Convert sat/byte to sat/KB
        );
      }

      // Prepare transaction (this handles coin selection and fee calculation)
      Logging.instance.log(Level.debug, "Preparing transaction...");
      final preparedTxData = await wallet.prepareSend(txData: txData);
      
      if (preparedTxData.fee == null) {
        throw Exception("Failed to calculate transaction fee");
      }

      // Build and sign transaction
      Logging.instance.log(Level.debug, "Building and signing transaction...");
      final builtTxData = await wallet.buildTransaction(
        txData: preparedTxData,
      );

      if (builtTxData.raw == null || builtTxData.raw!.isEmpty) {
        throw Exception("Failed to build transaction");
      }

      Logging.instance.log(Level.info, "Successfully created self-spend transaction");
      Logging.instance.log(Level.debug, "Transaction fee: ${builtTxData.fee?.toSerializeableString()}");
      
      return builtTxData;
    } catch (e) {
      Logging.instance.log(Level.error, "Failed to create self-spend transaction: $e");
      rethrow;
    }
  }

  /// Validates transaction was properly created and signed
  Future<bool> validateTransaction(TxData txData) async {
    try {
      Logging.instance.log(Level.debug, "Validating transaction...");
      
      // Check that transaction has raw data
      if (txData.raw == null || txData.raw!.isEmpty) {
        Logging.instance.log(Level.error, "Transaction has no raw data");
        return false;
      }

      // Check that transaction has a fee
      if (txData.fee == null || txData.fee! <= Amount.zero) {
        Logging.instance.log(Level.error, "Transaction has invalid fee");
        return false;
      }

      // Check that transaction has recipients
      if (txData.recipients == null || txData.recipients!.isEmpty) {
        Logging.instance.log(Level.error, "Transaction has no recipients");
        return false;
      }

      // Validate recipient amounts sum up correctly (basic sanity check)
      Amount totalRecipientAmount = Amount.zero;
      for (final recipient in txData.recipients!) {
        totalRecipientAmount += recipient.amount;
      }

      if (totalRecipientAmount <= Amount.zero) {
        Logging.instance.log(Level.error, "Total recipient amount is invalid");
        return false;
      }

      // For UTXO-based wallets, check that we have UTXOs selected
      if (txData.utxos != null && txData.utxos!.isEmpty) {
        Logging.instance.log(Level.warning, "Transaction has no UTXOs selected (may be normal for some coin types)");
      }

      Logging.instance.log(Level.info, "Transaction validation passed");
      return true;
    } catch (e) {
      Logging.instance.log(Level.error, "Transaction validation error: $e");
      return false;
    }
  }

  /// Attempts to broadcast transaction (use with extreme caution!)
  Future<String?> broadcastTransaction(Wallet wallet, TxData txData) async {
    try {
      Logging.instance.log(Level.warning, "BROADCASTING TRANSACTION - THIS WILL SPEND REAL FUNDS!");
      
      // Only broadcast if explicitly enabled and we're on testnet
      // This is intentionally commented out for safety
      // 
      // final confirmedTxData = await wallet.confirmSend(txData: txData);
      // return confirmedTxData.txid;
      
      throw Exception("Transaction broadcasting is disabled for safety in test environment");
    } catch (e) {
      Logging.instance.log(Level.error, "Failed to broadcast transaction: $e");
      rethrow;
    }
  }

  /// Checks if wallet has sufficient balance for testing
  Future<bool> hasMinimumBalanceForTesting(Wallet wallet, Amount minimumAmount) async {
    try {
      final balance = await wallet.balance;
      return balance.spendable >= minimumAmount;
    } catch (e) {
      Logging.instance.log(Level.error, "Failed to check wallet balance: $e");
      return false;
    }
  }

  /// Gets recommended test amount based on wallet balance
  Future<Amount?> getRecommendedTestAmount(Wallet wallet) async {
    try {
      final balance = await wallet.balance;
      
      if (balance.spendable <= Amount.zero) {
        return null;
      }

      // Use 1% of spendable balance or minimum coin amount, whichever is larger
      final onePercent = balance.spendable ~/ BigInt.from(100);
      final minCoinAmount = Amount(
        rawValue: BigInt.one,
        fractionDigits: wallet.cryptoCurrency.fractionDigits,
      );

      return onePercent > minCoinAmount ? Amount(
        rawValue: onePercent,
        fractionDigits: wallet.cryptoCurrency.fractionDigits,
      ) : minCoinAmount;
    } catch (e) {
      Logging.instance.log(Level.error, "Failed to calculate recommended test amount: $e");
      return null;
    }
  }
}