/* 
 * This file is part of Stack Wallet.
 * 
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'dart:io';
import 'package:logger/logger.dart';
import 'package:path/path.dart' as path;

import '../../../db/drift/database.dart';
import '../../../models/isar/models/isar_models.dart';
import '../../../services/node_service.dart';
import '../../../services/wallets.dart';
import '../../../utilities/flutter_secure_storage_interface.dart';
import '../../../utilities/logger.dart';
import '../../../utilities/prefs.dart';
import '../../../utilities/stack_file_system.dart';
import '../../../wallets/crypto_currency/crypto_currency.dart';
import '../../../wallets/models/wallet_info.dart';
import '../../../wallets/wallet/wallet.dart';
import 'backup_file_handler.dart';

class WalletRestorationManager {
  static const String _testDbSuffix = '_test';
  static const String _testWalletPrefix = 'test_';
  
  MainDB? _testDatabase;
  final List<String> _createdTestWalletIds = [];
  final List<Wallet> _restoredWallets = [];

  /// Creates isolated test database instance
  Future<MainDB> createTestDatabase() async {
    try {
      if (_testDatabase != null) {
        return _testDatabase!;
      }

      Logging.instance.log(Level.info, "Creating test database instance");
      
      // Get a unique test database path
      final testDbPath = await _getTestDatabasePath();
      
      // Create test database
      _testDatabase = await MainDB.init(
        filePath: testDbPath,
        name: "stack_wallet_test",
      );
      
      Logging.instance.log(Level.info, "Test database created at: $testDbPath");
      return _testDatabase!;
    } catch (e) {
      Logging.instance.log(Level.error, "Failed to create test database: $e");
      rethrow;
    }
  }

  /// Restores wallet from backup data in test environment
  Future<Wallet> restoreTestWallet(
    WalletBackupData walletData,
    MainDB testDB,
    SecureStorageInterface secureStorage,
    NodeService nodeService,
    Prefs prefs,
  ) async {
    try {
      Logging.instance.log(Level.info, "Restoring test wallet: ${walletData.name} (${walletData.coinName})");
      
      // Generate test wallet ID to avoid conflicts
      final testWalletId = '${_testWalletPrefix}${DateTime.now().millisecondsSinceEpoch}_${walletData.id}';
      _createdTestWalletIds.add(testWalletId);

      // Get crypto currency for the wallet
      final cryptoCurrency = _getCryptoCurrencyFromCoinName(walletData.coinName);
      if (cryptoCurrency == null) {
        throw Exception("Unsupported coin type: ${walletData.coinName}");
      }

      // Create wallet info
      final walletInfo = WalletInfo(
        walletId: testWalletId,
        name: '${_testWalletPrefix}${walletData.name}',
        walletType: _getWalletType(cryptoCurrency, walletData),
        coin: cryptoCurrency,
        otherDataJsonString: walletData.otherData['otherDataJsonString'] as String?,
        cachedBalanceString: '{"spendable":"0","blockedTotal":"0","pendingSpendable":"0","total":"0"}',
        favouriteOrderIndex: -1,
        restoreHeight: walletData.restoreHeight ?? 0,
      );

      // Store mnemonic or private key securely for testing
      if (walletData.mnemonic != null) {
        await secureStorage.write(
          key: '${testWalletId}_mnemonic',
          value: walletData.mnemonic!,
        );
        
        if (walletData.mnemonicPassphrase != null) {
          await secureStorage.write(
            key: '${testWalletId}_mnemonicPassphrase',
            value: walletData.mnemonicPassphrase!,
          );
        }
      }

      if (walletData.privateKey != null) {
        await secureStorage.write(
          key: '${testWalletId}_privateKey',
          value: walletData.privateKey!,
        );
      }

      // Create the wallet instance
      final wallet = await Wallet.create(
        walletInfo: walletInfo,
        mainDB: testDB,
        secureStorageInterface: secureStorage,
        nodeService: nodeService,
        prefs: prefs,
        mnemonic: walletData.mnemonic,
        mnemonicPassphrase: walletData.mnemonicPassphrase,
        privateKey: walletData.privateKey,
      );

      _restoredWallets.add(wallet);
      
      Logging.instance.log(Level.info, "Successfully restored test wallet: ${wallet.info.name}");
      return wallet;
    } catch (e) {
      Logging.instance.log(Level.error, "Failed to restore test wallet ${walletData.name}: $e");
      rethrow;
    }
  }

  /// Sets up test-specific node connections
  Future<void> configureTestNodes(List<dynamic> nodeData) async {
    try {
      Logging.instance.log(Level.info, "Configuring test nodes (${nodeData.length} nodes)");
      
      // For testing, we'll use default nodes to avoid complications
      // In a production implementation, you might want to set up specific test nodes
      Logging.instance.log(Level.info, "Using default node configurations for testing");
    } catch (e) {
      Logging.instance.log(Level.error, "Failed to configure test nodes: $e");
      rethrow;
    }
  }

  /// Validates wallet is ready for testing
  Future<bool> validateWalletHealth(Wallet wallet) async {
    try {
      Logging.instance.log(Level.info, "Validating wallet health: ${wallet.info.name}");
      
      // Check if wallet can generate addresses
      final receiveAddress = await wallet.getCurrentReceivingAddress();
      if (receiveAddress == null) {
        Logging.instance.log(Level.warning, "Wallet cannot generate receive address");
        return false;
      }

      // Check if wallet has transaction preparation capabilities
      if (!wallet.hasTransactionCaching) {
        Logging.instance.log(Level.info, "Wallet does not support transaction caching - may limit testing");
      }

      // For UTXO-based coins, try to refresh UTXOs
      try {
        await wallet.refresh();
        Logging.instance.log(Level.info, "Wallet refresh completed successfully");
      } catch (e) {
        Logging.instance.log(Level.warning, "Wallet refresh failed (may be normal for test environment): $e");
      }

      Logging.instance.log(Level.info, "Wallet health validation passed: ${wallet.info.name}");
      return true;
    } catch (e) {
      Logging.instance.log(Level.error, "Wallet health validation failed: $e");
      return false;
    }
  }

  /// Cleans up test wallets and database
  Future<void> cleanup() async {
    try {
      Logging.instance.log(Level.info, "Starting test environment cleanup");

      // Close and dispose of restored wallets
      for (final wallet in _restoredWallets) {
        try {
          Logging.instance.log(Level.debug, "Disposing wallet: ${wallet.info.name}");
          // Most wallets have cleanup in their dispose methods
        } catch (e) {
          Logging.instance.log(Level.warning, "Error disposing wallet ${wallet.info.name}: $e");
        }
      }
      _restoredWallets.clear();

      // Close test database
      if (_testDatabase != null) {
        await _testDatabase!.close();
        _testDatabase = null;
        Logging.instance.log(Level.info, "Test database closed");
      }

      // Remove test database files
      try {
        final testDbPath = await _getTestDatabasePath();
        final dbFile = File(testDbPath);
        if (await dbFile.exists()) {
          await dbFile.delete();
          Logging.instance.log(Level.info, "Test database file deleted");
        }
      } catch (e) {
        Logging.instance.log(Level.warning, "Failed to delete test database file: $e");
      }

      // Clear stored test wallet IDs
      _createdTestWalletIds.clear();

      Logging.instance.log(Level.info, "Test environment cleanup completed");
    } catch (e) {
      Logging.instance.log(Level.error, "Error during cleanup: $e");
    }
  }

  /// Gets the path for test database
  Future<String> _getTestDatabasePath() async {
    final appDir = await StackFileSystem.applicationSupportDirectory();
    final timestamp = DateTime.now().millisecondsSinceEpoch;
    return path.join(appDir.path, "test_db_$timestamp.sqlite");
  }

  /// Maps coin name to CryptoCurrency
  CryptoCurrency? _getCryptoCurrencyFromCoinName(String coinName) {
    switch (coinName.toLowerCase()) {
      case 'bitcoin':
        return Bitcoin.mainnet;
      case 'litecoin':
        return Litecoin.mainnet;
      case 'dogecoin':
        return Dogecoin.mainnet;
      case 'firo':
        return Firo.mainnet;
      case 'monero':
        return Monero.mainnet;
      case 'wownero':
        return Wownero.mainnet;
      case 'epiccash':
        return Epiccash.mainnet;
      case 'ethereum':
        return Ethereum.mainnet;
      case 'bitcoincash':
        return Bitcoincash.mainnet;
      default:
        return null;
    }
  }

  /// Determines wallet type from crypto currency and backup data
  WalletType _getWalletType(CryptoCurrency crypto, WalletBackupData walletData) {
    // Check if it's a multisig wallet
    if (walletData.otherData.containsKey('frostWalletData')) {
      return WalletType.cryptoCurrencyFrost;
    }
    
    // Default to standard wallet
    return WalletType.cryptoCurrency;
  }

  // Getters for current state
  List<String> get createdTestWalletIds => List.unmodifiable(_createdTestWalletIds);
  List<Wallet> get restoredWallets => List.unmodifiable(_restoredWallets);
  bool get hasActiveTestEnvironment => _testDatabase != null || _restoredWallets.isNotEmpty;
}