/*
 * This file is part of Stack Wallet.
 *
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import '../../models/isar/models/isar_models.dart';
import '../../wallets/wallet/impl/namecoin_wallet.dart';
import '../../wallets/wallet/wallet.dart';

extension UTXOConfirmedStatus on UTXO {
  bool isConfirmedStatus(int currentChainHeight, Wallet wallet) {
    if (wallet is NamecoinWallet) {
      return wallet.checkUtxoConfirmed(this, currentChainHeight);
    } else {
      return isConfirmed(
        currentChainHeight,
        wallet.cryptoCurrency.minConfirms,
        wallet.cryptoCurrency.minCoinbaseConfirms,
      );
    }
  }
}
