/*
 * This file is part of Stack Wallet.
 *
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

/// Parsed data from a `monero_wallet:` URI used for wallet restoration.
///
/// Supports two variants:
///   - Seed restore:
///     `monero_wallet:?seed=word1+word2+...&height=123456`
///   - View-key restore:
///     `monero_wallet:<address>?view_key=<hex>&height=123456`
class MoneroWalletUriData {
  final String? seed;
  final String? address;
  final String? privateViewKey;
  final int? height;

  const MoneroWalletUriData._({
    this.seed,
    this.address,
    this.privateViewKey,
    this.height,
  });

  /// Whether this URI represents a seed-based restore.
  bool get isSeedRestore => seed != null && seed!.isNotEmpty;

  /// Whether this URI represents a view-key-based restore.
  bool get isViewKeyRestore =>
      address != null &&
      address!.isNotEmpty &&
      privateViewKey != null &&
      privateViewKey!.isNotEmpty;

  /// Parse a `monero_wallet:` URI string.
  ///
  /// Returns `null` if [uriString] is not a valid `monero_wallet:` URI.
  static MoneroWalletUriData? parse(String uriString) {
    final trimmed = uriString.trim();

    // Must start with the monero_wallet: scheme.
    if (!trimmed.startsWith('monero_wallet:')) {
      return null;
    }

    // Remove the scheme prefix to get the remainder.
    final afterScheme = trimmed.substring('monero_wallet:'.length);

    String? address;
    String queryString;

    // Determine if this is a view-key URI (has an address path before ?)
    // or a seed URI (starts with ? directly).
    final queryIndex = afterScheme.indexOf('?');
    if (queryIndex == -1) {
      // No query string at all — not a valid restore URI.
      return null;
    }

    if (queryIndex > 0) {
      // There is a path component (address) before the query string.
      address = afterScheme.substring(0, queryIndex);
    }
    queryString = afterScheme.substring(queryIndex + 1);

    // Parse query parameters manually (Uri class doesn't handle custom schemes
    // well in all Dart versions).
    final params = _parseQueryString(queryString);

    final seedRaw = params['seed'];
    final viewKey = params['view_key'];
    final heightStr = params['height'];

    // URL-decode the seed: '+' becomes space, and handle %XX encoding.
    final String? seed;
    if (seedRaw != null && seedRaw.isNotEmpty) {
      seed = Uri.decodeComponent(seedRaw.replaceAll('+', ' ')).trim();
    } else {
      seed = null;
    }

    final int? height;
    if (heightStr != null && heightStr.isNotEmpty) {
      height = int.tryParse(heightStr);
    } else {
      height = null;
    }

    // Validate: must be either a seed restore or a view-key restore.
    final data = MoneroWalletUriData._(
      seed: seed,
      address: address,
      privateViewKey: viewKey,
      height: height,
    );

    if (!data.isSeedRestore && !data.isViewKeyRestore) {
      return null;
    }

    return data;
  }

  /// Parse a query string into a map of key-value pairs.
  static Map<String, String> _parseQueryString(String query) {
    final result = <String, String>{};
    if (query.isEmpty) return result;

    for (final part in query.split('&')) {
      final eqIndex = part.indexOf('=');
      if (eqIndex == -1) {
        result[part] = '';
      } else {
        final key = part.substring(0, eqIndex);
        final value = part.substring(eqIndex + 1);
        result[key] = value;
      }
    }
    return result;
  }
}
