/* 
 * This file is part of Stack Wallet.
 * 
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'dart:io';

import 'package:path/path.dart' as path;
import 'package:path_provider/path_provider.dart';

import '../app_config.dart';
import 'prefs.dart';
import 'util.dart';

abstract class StackFileSystem {
  static String? _overrideDesktopDirPath;
  static bool _overrideDirSet = false;
  static bool _isPortable = false;

  static bool get isPortableMode => _isPortable;

  static void setDesktopOverrideDir(String dirPath, {bool portable = false}) {
    if (_overrideDirSet) {
      throw Exception(
        "Attempted to change StackFileSystem._overrideDir unexpectedly",
      );
    }
    _overrideDesktopDirPath = dirPath;
    _overrideDirSet = true;
    _isPortable = portable;
  }

  /// Detects whether the app is running on a privacy focused, amnesic, or
  /// otherwise portable oriented Linux distribution such as Whonix or Tails.
  ///
  /// On such systems the user's home directory is typically not persistent, so
  /// data should be stored beside the AppImage instead. All file reads are
  /// wrapped in try/catch so that a missing file or permission error never
  /// crashes startup; the worst case simply returns false.
  static bool isAmnesicOrPortableDistro() {
    if (!Platform.isLinux) {
      return false;
    }

    // Whonix markers.
    try {
      if (File("/etc/whonix_version").existsSync() ||
          Directory("/usr/share/whonix").existsSync()) {
        return true;
      }
    } catch (_) {
      // Ignore and continue checking other markers.
    }

    // Whonix uses well known hostnames such as 'host' or 'anon-...'.
    try {
      final hostname = Platform.localHostname.toLowerCase();
      if (hostname == "host" || hostname.startsWith("anon-")) {
        return true;
      }
    } catch (_) {
      // Ignore and continue checking other markers.
    }

    // Tails markers.
    try {
      if (File("/etc/amnesia").existsSync() ||
          Directory("/live").existsSync()) {
        return true;
      }
    } catch (_) {
      // Ignore and continue checking other markers.
    }

    try {
      final osRelease = File("/etc/os-release");
      if (osRelease.existsSync() &&
          osRelease.readAsStringSync().toLowerCase().contains("tails")) {
        return true;
      }
    } catch (_) {
      // Ignore; absence or read failure simply means no match.
    }

    return false;
  }

  /// The path to the directory containing the running AppImage, or null if the
  /// app is not running as an AppImage.
  static String? get appImageDirectoryPath {
    if (!Platform.isLinux) {
      return null;
    }
    final appImagePath = Platform.environment['APPIMAGE'];
    if (appImagePath == null) {
      return null;
    }
    return path.dirname(appImagePath);
  }

  /// Whether the app is running as an AppImage and so can support the manual
  /// portable mode toggle (which works by writing a marker beside the binary).
  static bool get canTogglePortableMode => appImageDirectoryPath != null;

  static File? _portableMarkerFile() {
    final dir = appImageDirectoryPath;
    if (dir == null) {
      return null;
    }
    return File(path.join(dir, ".portable"));
  }

  /// Creates or removes the `.portable` marker beside the AppImage. The change
  /// only takes effect on the next launch, since the data directory is chosen
  /// during startup before this can be called. Returns true on success.
  static bool setPortableMarker(bool enabled) {
    final marker = _portableMarkerFile();
    if (marker == null) {
      return false;
    }
    try {
      if (enabled) {
        if (!marker.existsSync()) {
          marker.createSync(recursive: true);
        }
      } else {
        if (marker.existsSync()) {
          marker.deleteSync();
        }
      }
      return true;
    } catch (_) {
      return false;
    }
  }

  static bool get _createSubDirs =>
      Util.isDesktop || AppConfig.appName == "Campfire";

  static Future<Directory> applicationRootDirectory() async {
    Directory appDirectory;

    // todo: can merge and do same as regular linux home dir?
    if (Util.isArmLinux) {
      appDirectory = await getApplicationDocumentsDirectory();
      appDirectory = Directory(
        path.join(appDirectory.path, ".${AppConfig.appDefaultDataDirName}"),
      );
    } else if (Platform.isLinux) {
      if (_overrideDesktopDirPath != null) {
        appDirectory = Directory(_overrideDesktopDirPath!);
      } else {
        appDirectory = Directory(
          path.join(
            Platform.environment['HOME']!,
            ".${AppConfig.appDefaultDataDirName}",
          ),
        );
      }
    } else if (Platform.isWindows) {
      if (_overrideDesktopDirPath != null) {
        appDirectory = Directory(_overrideDesktopDirPath!);
      } else {
        appDirectory = await getApplicationSupportDirectory();
      }
    } else if (Platform.isMacOS) {
      if (_overrideDesktopDirPath != null) {
        appDirectory = Directory(_overrideDesktopDirPath!);
      } else {
        appDirectory = await getLibraryDirectory();
        appDirectory = Directory(
          path.join(appDirectory.path, AppConfig.appDefaultDataDirName),
        );
      }
    } else if (Platform.isIOS) {
      // todo: check if we need different behaviour here
      if (Util.isDesktop) {
        appDirectory = await getLibraryDirectory();
      } else {
        appDirectory = await getLibraryDirectory();
      }
    } else if (Platform.isAndroid) {
      appDirectory = await getApplicationDocumentsDirectory();
    } else {
      throw Exception("Unsupported platform");
    }
    if (!appDirectory.existsSync()) {
      await appDirectory.create(recursive: true);
    }
    return appDirectory;
  }

  static Future<Directory> applicationIsarDirectory() async {
    final root = await applicationRootDirectory();
    if (_createSubDirs) {
      final dir = Directory(path.join(root.path, "isar"));
      if (!dir.existsSync()) {
        await dir.create();
      }
      return dir;
    } else {
      return root;
    }
  }

  static Future<Directory> applicationDriftDirectory() async {
    final root = await applicationRootDirectory();
    if (_createSubDirs) {
      final dir = Directory(path.join(root.path, "drift"));
      if (!dir.existsSync()) {
        await dir.create();
      }
      return dir;
    } else {
      return root;
    }
  }

  // Not used in general now. See applicationFiroCacheSQLiteDirectory()
  // static Future<Directory> applicationSQLiteDirectory() async {
  //   final root = await applicationRootDirectory();
  //   if (_createSubDirs) {
  //     final dir = Directory("${root.path}/sqlite");
  //     if (!dir.existsSync()) {
  //       await dir.create();
  //     }
  //     return dir;
  //   } else {
  //     return root;
  //   }
  // }

  static Future<Directory> applicationTorDirectory() async {
    final root = await applicationRootDirectory();
    if (_createSubDirs) {
      final dir = Directory(path.join(root.path, "tor"));
      if (!dir.existsSync()) {
        await dir.create();
      }
      return dir;
    } else {
      return root;
    }
  }

  static Future<Directory> applicationMwebdDirectory(String network) async {
    final root = await applicationRootDirectory();
    final dir = Directory(path.join(root.path, "mwebd", network));
    if (!dir.existsSync()) {
      await dir.create(recursive: true);
    }
    return dir;
  }

  static Future<Directory> applicationFiroCacheSQLiteDirectory() async {
    final root = await applicationRootDirectory();
    if (_createSubDirs) {
      final dir = Directory(path.join(root.path, "sqlite", "firo_cache"));
      if (!dir.existsSync()) {
        await dir.create(recursive: true);
      }
      return dir;
    } else {
      return root;
    }
  }

  static Future<Directory> applicationHiveDirectory() async {
    final root = await applicationRootDirectory();
    if (_createSubDirs) {
      final dir = Directory(path.join(root.path, "hive"));
      if (!dir.existsSync()) {
        await dir.create();
      }
      return dir;
    } else {
      return root;
    }
  }

  static Future<Directory> applicationXelisDirectory() async {
    final root = await applicationRootDirectory();
    final dir = Directory(path.join(root.path, "xelis"));
    if (!dir.existsSync()) {
      await dir.create();
    }
    return dir;
  }

  static Future<Directory> applicationXelisTableDirectory() async {
    final xelis = await applicationXelisDirectory();
    final dir = Directory(path.join(xelis.path, "table"));
    if (!dir.existsSync()) {
      await dir.create();
    }
    return dir;
  }

  static Future<void> initThemesDir() async {
    final root = await applicationRootDirectory();

    final dir = Directory(path.join(root.path, "themes"));
    if (!dir.existsSync()) {
      await dir.create();
    }
    themesDir = dir;
  }

  static Directory? themesDir;

  static Future<Directory> applicationLogsDirectory(Prefs prefs) async {
    // if prefs logs path is set, use that
    if (prefs.logsPath != null) {
      final dir = Directory(prefs.logsPath!);
      if (await dir.exists()) {
        return dir;
      }
    }

    final Directory logsDir;

    if (_overrideDesktopDirPath != null) {
      logsDir = Directory(path.join(_overrideDesktopDirPath!, "logs"));
    } else {
      final appDocsDir = await getApplicationDocumentsDirectory();
      const logsDirName = "${AppConfig.prefix}_Logs";

      if (Platform.isIOS) {
        logsDir = Directory(path.join(appDocsDir.path, "logs"));
      } else if (Platform.isMacOS || Platform.isLinux || Platform.isWindows) {
        // TODO check this is correct for macos
        logsDir = Directory(path.join(appDocsDir.path, logsDirName));
      } else if (Platform.isAndroid) {
        logsDir = Directory(path.join(appDocsDir.path, "logs"));
      } else {
        throw Exception("Unsupported Platform");
      }
    }

    if (!logsDir.existsSync()) {
      await logsDir.create(recursive: true);
    }

    return logsDir;
  }
}
